### ISSUE TITLE
Don't bundle unused icon paths

### ISSUE THREAD

**Issue by dphilipson** [palantir/blueprint#3453] opened 2019-03-28 16:53 UTC
#### Environment

- __Package version(s)__: 3.14.1
- __Browser and OS versions__: N/A

#### Feature request

Currently, Blueprint bundles all icon SVG paths even if they aren't used. For example, in an app which uses `Button` as the only import from Blueprint, we see this from source-map-explorer:

![image](https://user-images.githubusercontent.com/1661903/55176725-e7c85980-513e-11e9-878c-6856ec2b180e.png)

Note that Blueprint contributes 380kb, but 359kb of it is just the SVG paths even though I don't use any icons in my app. Finding a way to not do this would be nice.

Unfortunately, I don't see an elegant way to do this with the current API. It's not pretty, but exposing iconless versions of components would work, e.g. `IconlessButton` which doesn't have an `icon` prop and doesn't import `Icon`. Also, Blueprint could expose an alternate icon component, say `EcoFriendlyIcon`, which instead of taking a string `icon` prop (which needs all paths to be bundled to enable runtime lookup) actually takes the path itself, and then individual paths could be imported and the rest treeshaken.

**Comment by adidahiya** [comment] 2019-03-28 20:32
duplicate of #2193

**Closed by adidahiya** 2019-03-28 20:32 UTC
