### ISSUE TITLE
[React 18] `Toaster.create()` still using ReactDOM.render

### ISSUE THREAD

**Issue by ptgamr** [palantir/blueprint#5315] opened 2022-05-24 04:03 UTC
#### Environment

- __Package version(s)__: 4.3.2
- React: 18.1.0

#### Steps to reproduce

```
Toaster.create({position: Position.TOP})
```

#### Actual behavior

Got an error

```
ReactDOM.render is no longer supported in React 18. Use createRoot instead
```

#### Possible solution

`Toaster.create` still using `ReactDOM.render` https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/toast/toaster.tsx#L133

We can perhaps fix it by using `createRoot`, but `root.render()` is just a void function, it no longer returns a React Element. So we might have to figure out how to get access to the returned instance here.

Not sure how it should be going forward, if Blueprint still need to support older version of React... Maybe we will need `Toaster2` that can only be used with React 18

**Comment by adidahiya** [comment] 2022-05-25 13:43
duplicate of https://github.com/palantir/blueprint/issues/5212

**Closed as completed by adidahiya** 2022-05-25 13:43 UTC
Labels: Resolution: duplicate
