### ISSUE TITLE
Does blueprint has a componeny library for VueJs?

### ISSUE THREAD

**Issue by JenuelDev** [palantir/blueprint#4817] opened 2021-07-24 15:03 UTC
#### Question
Does blueprint has a component library for Vue 3 or vuejs?

**Comment by adidahiya** [comment] 2021-07-26 15:36
No, this is a duplicate of https://github.com/palantir/blueprint/issues/4677 (seems like you asked the same question a few months back).

**Closed as completed by adidahiya** 2021-07-26 15:36 UTC
Labels: Resolution: duplicate
