### ISSUE TITLE
Multi-row selection cut off during scrolling

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#950] opened 2017-04-05 16:28 UTC
When selecting more than what's visible at a time by scrolling during selection, the selection is cut off at the bottom to what's currently visible, see gif:
![bluprint-table-bug](https://cloud.githubusercontent.com/assets/42910/24715904/07f288fc-19e2-11e7-81ab-50395085ffb6.gif)

**Comment by llorca** [comment] 2017-04-05 16:32
We have a bunch of scrolling issues at the moment. Essentially a dupe of #505

**Comment by invliD** [comment] 2017-04-05 16:35
@llorca I don't think it's a duplicate. That issue describes the missing scrolling when dragging outside of the visible area (a feature request), this one describes a bug that already happens when scrolling outside manually.
The bug described here is visible in Adi's gif, but not mentioned at all.

**Comment by llorca** [comment] 2017-04-05 17:50
I just tried to repro these scrolling problems.

- When you drag outside of the visible area (feature request if you want, it's more of a bug/enhancement) horizontally, there's no scroll happening. That's the first issue here.
- When you drag outside of the visible area vertically, there is scroll happening, therefore the problem is different from previously. What happens is the same thing that your GIF is showing.
- Finally, there's the issue you describe when selecting a region while scrolling at the same time.

That's essentially 3 different facets of the same scrolling bug. I'm pretty sure it's a duplicate, but I'll reopen in case I'm mistaken and others can take a look at it

**Comment by invliD** [comment] 2017-04-05 17:52
I can't confirm (2). Neither in the docs examples nor our internal product is there any scrolling when dragging the selection outside of the visible area, neither horizontally nor vertically.

**Comment by llorca** [comment] 2017-04-05 18:00
That's what I mean by 2. Tested it some more, looks like it's only a Safari thing at the moment. Still, we'll be mindful of that when we get to scrolling issues

![vertical](https://cloud.githubusercontent.com/assets/199754/24719555/03172e3e-19ef-11e7-865b-1b4a9c2a78af.gif)

**Comment by adidahiya** [comment] 2017-04-05 20:36
Yeah it's pretty similar to #505 and any good solution ought to fix both this and that issue. I don't mind keeping both tickets around though

**Closed** 2017-05-18 18:41 UTC
Labels: Package: table, Status: accepting PRs, Type: enhancement
