### ISSUE TITLE
<ControlGroup /> overlaps Popup of <DateInput />

### ISSUE THREAD

**Issue by giftkugel** [palantir/blueprint#2368] opened 2018-04-06 08:16 UTC
### Bug report

- __Package version(s)__: 
```
    "react": "16.3.1",
    "react-dom": "16.3.1",
    "@blueprintjs/core": "2.1.1",
    "@blueprintjs/datetime": "2.0.2",
    "@blueprintjs/icons": "2.1.1",
    "@blueprintjs/select": "2.0.0"
```
- __Browser and OS versions__:  Chrome 59.0.3071.115 (OS independent)

#### Steps to reproduce

Create a `<ControlGroup />` with an `<DateInput />` inside, followed by another `<ControlGroup />` with an `<InputGroup />`

#### Actual behavior

The `<InputGroup />` will overlap the Popup of the `<DateInput />`
![blueprintjs_overlap](https://user-images.githubusercontent.com/9103924/38409664-8910291a-3982-11e8-962a-039538a410ff.png)

#### Expected behavior

It should not overlap.
![blueprintjs_overlap_fixed](https://user-images.githubusercontent.com/9103924/38409769-f64b7a98-3982-11e8-8df8-a4e7bc2a0b3c.png)

#### Notes
The behavior is caused by the
```
-webkit-transform: translateZ(0);
transform: translateZ(0);
```
CSS rule added to the `pt-control-group` after removing the transform statement, the overlap seems to be fixed.

**Comment by llorca** [comment] 2018-05-02 23:47
@giftkugel any reason why this popover needs to be inline? if you use `popoverProps: { usePortal: true }`, it should work (it's already the default behavior)

**Comment by llorca** [comment] 2018-05-21 21:29
dupe of https://github.com/palantir/blueprint/issues/2505

**Closed by llorca** 2018-05-21 21:29 UTC
