### ISSUE TITLE
Columns not rendering in scrolling table

### ISSUE THREAD

**Issue by towler73** [palantir/blueprint#4105] opened 2020-04-30 15:54 UTC
#### Environment

- __Package version(s)__: @blueprintjs/core: 3.9.0, @blueprintjs/table 3.8.4
- __Browser and OS versions__: Chrome and Safari, Mac and Windows

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-sb071?file=/src/CoreExample.tsx

#### Steps to reproduce

1. Make browser wide enough to show Zip column, but not Comment column
1. Refresh browser window
1. Data loads after 2 sec delay, by setting state in parent component, which is passed down as property. 
1. Zip and Comment columns aren't displayed.  If you scroll, they appear.

#### Actual behavior

If Table height and width is set forcing scroll bar,
some columns not displayed after load until you scroll the table.

#### Expected behavior

All visible columns should load.

#### Possible solution

Not sure what's happening.  I see that the table has the correct list of Columns in it's props, but I don't see all the columns in the Component tree until I scroll, then they pop up.

**Comment by adidahiya** [comment] 2020-04-30 16:31
duplicate of #3779. for now I recommend downgrading to table 3.7.x

**Closed by adidahiya** 2020-04-30 16:31 UTC
Labels: Resolution: duplicate

**Comment by towler73** [comment] 2020-04-30 17:46
Oh, sorry about that.  I guess I didn't search deep enough into issues.  Thanks for the workaround.
