### ISSUE TITLE
Example yarn install for Windows 10

### ISSUE THREAD

**Issue by YuK1Game** [palantir/blueprint#3800] opened 2019-10-30 06:45 UTC
```
$ git clone https://github.com/palantir/blueprint
$ cd blueprint/package/doc-app
$ yarn install

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\UserName\Desktop\blueprint\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\UserName\\Desktop\\blueprint\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\UserName\Desktop\blueprint\node_modules\tree-sitter-typescript
```

**Comment by nicholas-l** [comment] 2019-10-31 13:08
Looks like it's related to #3799

**Comment by adidahiya** [comment] 2019-11-03 20:48
duplicate of #3799

**Closed by adidahiya** 2019-11-03 20:48 UTC
