### ISSUE TITLE
onClick event is fired twice for <Button> when button is clicked with spacebar in Firefox

### ISSUE THREAD

**Issue by ttaranov** [palantir/blueprint#4231] opened 2020-07-19 23:40 UTC
#### Environment

- 3.0.30
- MacOS Catalina 10.15.5
- Firefox 78.0.2

#### Code Sandbox

https://codesandbox.io/s/double-click-with-spacebar-in-firefox-evx78?file=/src/index.tsx

#### Steps to reproduce

1) tab to blueprint button in browser 
2) press it with keyboard spacebar

#### Actual behavior

onClick event is fired twice

#### Expected behavior

onClick should fire once, like it does in Chrome

#### Possible solution

I believe it has to do with this piece of code in abstractButton.tsx
```
    protected handleKeyUp = (e: React.KeyboardEvent<any>) => {
        if (Keys.isKeyboardClick(e.which)) {
            this.setState({ isActive: false });
            getRef(this.buttonRef).click();
        }
        this.currentKeyDown = null;
        this.props.onKeyUp?.(e);
    };
```

**Comment by adidahiya** [comment] 2020-07-21 18:36
Duplicate of #4170

**Closed as completed by adidahiya** 2020-07-21 18:36 UTC
Labels: Resolution: duplicate, Package: core
