### ISSUE TITLE
Popover did not close by escape key

### ISSUE THREAD

**Issue by olegshilov** [palantir/blueprint#4496] opened 2021-01-25 18:43 UTC
#### Environment

- __Package version(s)__: 3.38.1
- __Operating System__: macOS Big Sur 11.1
- __Browser name and version__: Google Chrome 88.0.4324.96

#### Code Sandbox

You can see this behavior at your docs site https://blueprintjs.com/docs/#core/components/popover

#### Steps to reproduce

1. Choose `Text` at example content select
2. Enable `Can escape key close` switcher
3. Open popover by clicking to `Popover target` button
4. Press the `Escape` button

#### Actual behavior

Popover did not close

#### Expected behavior

Popover dismissed

**Comment by adidahiya** [comment] 2021-01-26 01:47
duplicate of #4300

**Closed as completed by adidahiya** 2021-01-26 01:47 UTC
Labels: Resolution: duplicate

**Comment by tjmcdonough** [comment] 2024-04-04 08:43
This still happens even on your documentation https://mantine.dev/core/popover.

Name | Type | Description
-- | -- | --
`closeOnEscape` | `boolean` | `Determines whether dropdown should be closed when Escape key is pressed, true by default`
