### ISSUE TITLE
Popover2: Support virtual reference elements / follow cursor

### ISSUE THREAD

**Issue by tillprochaska** [palantir/blueprint#5826] opened 2023-01-05 13:36 UTC
#### Environment

- __Package version(s)__: 1.10.2
- __Browser and OS versions__: n/a

#### Feature request

We would like to implement a popover that follow the cursor position. We use the popovers with very wide targets (sometime wider than the viewport). When using a static position for the popover, there will be situations where the popover is displayed very far away from the users cursor/point of interaction, which can lead to a confusing UX.

It would be great if the Popover component could support one of the following options:

1. Support a separate boolean property `followCursor`). Enabling this property would use the mouse cursor position as the reference for positioning rather than the popover target. The target would still be used to trigger the popover on click or hover).

2. Support passing a custom reference element to Popper. This would allow for bigger flexibility with regards to the position of the overlay and would allow users to easily implement a "follow cursor" behavior.

#### Examples

[This example](https://popper.js.org/docs/v2/virtual-elements/) from the Popper.js docs shows the desired positioning behavior.

**Comment by adidahiya** [comment] 2023-01-05 15:22
Duplicate of https://github.com/palantir/blueprint/issues/4642

**Closed as completed by adidahiya** 2023-01-05 15:22 UTC
Labels: Resolution: duplicate, Package: popover2

**Comment by tillprochaska** [comment] 2023-01-06 09:43
@adidahiya Sorry, I somehow missed the other issue before 🙃
