### ISSUE TITLE
Popover Elements (Tooltip, Popover, Overlay) do not open with Portals

### ISSUE THREAD

**Issue by mulholo** [palantir/blueprint#3248] opened 2018-12-17 11:45 UTC
#### Environment

- __Package version(s)__: 3.10
- __Browser and OS versions__: Chrome, Firefox and Safari (latest). MacOS 10.14.1 (latest)

#### Steps to reproduce

1. Use `<Popover />` anywhere with `usePortal={true}` (default behaviour)
2. Click on the popover target

#### Actual behavior

- No popover content appears when clicked
-`bp3-popover-open` class still appears on the target
- No portal div appears at the bottom of the page
- Setting the `usePortal` prop to `true` gets rid of the bug.

#### Expected behaviour

- Popover opens within a portal div and is visible.

#### Possible solution

- I supect this is not a CSS issue as the problem seems to be that the portal div is not being added at all to the bottom of the page.

#### Other Information

- This bug occurred during an upgrade from Blueprint Version 3.6 to 3.10. Consequently, it seems likely that the error is due to one of the following, Portal-related pull requests:
  - #3213 
  - #3215 
  - #3200 
  - #3149 
  - #3148 
  - #3156 
  - #3045

**Comment by mulholio** [comment] 2018-12-19 11:49
Still not resolved, but we have found that by setting `portalContainer={document.body}` (the default) portals render correctly.

**Comment by mulholio** [comment] 2018-12-21 16:04
Thanks for the link. I have tried copying problematic code from two different parts of our app and haven't succeeded in reproducing the bug in Codesandbox. Given this, I suspect your analysis is correct and our environment is doing something strange.

Closing the issue, but was wondering if you had any ideas on what the cause might be?

**Comment by nikko242** [comment] 2019-02-14 10:07
I have the exact same behaviour as you @mulholio 

Have you figured out what was wrong in your environment, and how to fix it?

Regards
Niklas

**Comment by mulholio** [comment] 2019-02-14 10:43
@nikko242 no resolution yet. I'm just relying upon the `usePortal` prop for now as a work around. Give us a shout if you find a better fix!

**Comment by nikko242** [comment] 2019-02-15 07:37
Ok, thanks.

No, we also use usePortal together with portalContainer to make it work.

I have had a look at the code, and it seems strange to me that it could work on a different environment, it seems that portalContainer never gets set to "document.body" as default as stated in the documentation.

**Comment by mulholio** [comment] 2019-02-20 17:29
@nikko242 Any luck on this? Was hoping to resolve the issue just with `usePortal={false}` but the Overlay component is used behind the scenes on other Blueprint Components (e.g. Table Cell Context Menus) so we're running into still.

We've deleted all the CSS so it doesn't appear to be anything related to that.

I can find the underlying Portal and children in React dev-tools but mousing over just shows 0px x 0px at the top left and doesn't actually render the content on the page.

**Comment by mulholio** [comment] 2019-02-21 12:14
Further investigations:

- From inspecting Blueprint's source code and stepping through in dev tools, I can see that in the `<Portal />` render method the portal is only created if this condition is false:
https://github.com/palantir/blueprint/blob/3dcbb0113f7f58637dec57a85c445011d51bafb6/packages/core/src/components/portal/portal.tsx#L71
- In my app, the is true as `state.hasMounted` is false. This is because `props.container` is null (see `componendDidMount()` for this)

Still trying to work out why the container prop is missing.

**Comment by nikko242** [comment] 2019-02-22 13:26
We work around this, by manually settings portalContainer when Portal=true, it works .. but the code gets abit bloated:

`<Dialog
                   onClose={this.props.OnClose}
                    title="Ändra skipass"
            isOpen={true}
            usePortal={true}
            portalContainer={document.body}>...               
</Dialog>`

**Comment by nikko242** [comment] 2019-02-22 13:33
I have taken a look in the blueprinjs source code, and I think It would be quite easy to fix:

In "packages/core/src/components/overlay/overlay.tsx"
line: 231
`                <Portal className={this.props.portalClassName} container={this.props.portalContainer}>`
Change to:
`               <Portal className={this.props.portalClassName} container={this.props.portalContainer != null?this.props.portalContainer:document.body}>`

**Comment by mulholio** [comment] 2019-02-22 17:08
Would the Blueprint team be open to adding this to the Overlay component?

**Before:**
https://github.com/palantir/blueprint/blob/3dcbb0113f7f58637dec57a85c445011d51bafb6/packages/core/src/components/overlay/overlay.tsx#L231

**After:**
```jsx
<Portal
  className={this.props.portalClassName}
  container={this.props.portalContainer ? this.props.portalContainer : document.body}
>
```

At the very least, I feel like there should be some kind of error thrown if you try and create a portal with no container element referenced. As suggested by @nikko242 , `document.body` seems like a sensible default to create a portal on if none is explictly passed?

Happy to make a PR.

**Comment by adidahiya** [comment] 2019-02-25 00:56
@mulholio that default gets set further down the component stack: https://github.com/palantir/blueprint/blob/3dcbb0113f7f58637dec57a85c445011d51bafb6/packages/core/src/components/portal/portal.tsx#L59. so I don't think your suggested change would fix this.

but I will admit it's confusing for Overlay's docs to list `@default document.body` for its `portalContainer` prop when it doesn't actually do any default handling itself (only Portal does that).

**Comment by nikko242** [comment] 2019-02-25 10:38
ok, I have checked the portal.tsx code, the default value is set in defaultProps, but i cannot see that it is actually used, or am I missing something?

**Comment by chiubaka** [comment] 2019-04-04 13:58
I'm also encountering this issue. Setting `document.body` explicitly seems to resolve. If it helps, things break for me starting with `3.8.0`. They work in `3.7.0`. I'm therefore fairly certain the problem was introduced by #3045.

**Comment by adidahiya** [comment] 2019-04-04 23:41
If you are still seeing this issue can you create a repro of it in a code sandbox (see link in the README or issue template) or a small repo?

**Comment by chiubaka** [comment] 2019-04-29 03:14
This is still an issue for me. Trying to see what I can do to simplify my own configuration and pinpoint the issue. Thus far, my best guess is that it somehow has something to do with Rails + Webpacker + Blueprint... I'm unable to get even a simple example (page literally just displays a Popover Button, all other JS/TS/CSS/SCSS code has been removed, and all unnecessary packages have been removed) to work with this pipeline using the latest versions of everything.

Setting `document.body` explicitly still works, but I'm out of luck without that (and not all of the popover components expose the `portalContainer` prop, particularly the `DateInput` and the like, I think).

Any chance anyone else with this issue is using a similar setup? May try to see if I can create a fresh small repo with this, if for no other reason than to test my own sanity...

**Comment by chiubaka** [comment] 2019-04-29 04:04
[Here's the smallest possible Rails + Webpack + Blueprint repo I could create](https://github.com/chiubaka/blueprint-rails-webpack-test). To my chagrin, still seeing the issue here. I've done the absolute minimum of additional configuration outside of the defaults. Would love to hear that the Rails defaults just misconfigure Babel or Webpack somehow...

**Comment by chshanovskiy** [comment] 2019-05-01 11:35
Hi, i've encountered same issue with my own setup. Usually, bundle injected in end of body, and div#root is present in layout. 
But in my setup, I've injected bundle to head, and wrap my React.render with DOMContentLoaded. 
It's hard to reproduce on codesandbox, because of custom webpack-html-plugin options

When I reverted setup to "defaults", problem is gone.

Hope this would be helpful

**Comment by mulholio** [comment] 2019-05-02 07:31
@chiubaka we were getting this issue on a Rails app too so sounds like you might be onto something. I've left the project recently but @strickland84 may have some relevant details.

**Comment by chiubaka** [comment] 2019-05-02 13:20
Ah... well, that's interesting. So actually including `<%= javascript_pack_tag "application" %>` in the HTML `head` causes `document.body` to be initially `null` when all the scripts run. I think this is causing Blueprint some headache... likely there's some initialization code for the Portal that doesn't like this.

Moving `<%= javascript_pack_tag "application" %>` to the bottom of the `body` seems to solve the issue.

**Comment by adidahiya** [comment] 2019-05-16 03:20
Generally it's best practice to inject application scripts at the bottom of body anyway, so as to not block HTML rendering.

**Comment by tgalopin** [comment] 2021-11-07 21:33
I'm encountering this issue as well, but only when I'm using https://github.com/hotwired/turbo. Because of the way Turbo works, I put the script tags at the end of the head tag with the defer attribute. Given that people experiencing this issue seems to come from Rails, where Turbo originates from, it could make sense that the common denominator is the usage of Turbo.

By investigating a bit more, I think I have more details:

* when the issue occurs, it's because the original React element (from my app) doesn't seem to have a usable size on the page (as you can see in the following image, the React Dev Tools display NaN as a position/size for the element)
* the issue does *not* happen at the first load (ie when the page is loaded normally) but happens afterwards, when Turbo is used to load the page and replace its content
* the issue is resolved, even with Turbo, when using `portalContainer={document.body}`
* I'm using the 4.0-beta8

![image](https://user-images.githubusercontent.com/1651494/140662593-c1c23dc7-f867-445e-bb6a-7d6d0c659fd2.png)

I'm not sure what's the source cause but having `portalContainer={document.body}` fixing the problem is nice :) .

**Closed** 2022-08-04 18:43 UTC
Labels: Status: needs more info, Resolution: cannot reproduce, Resolution: aged away
