### ISSUE TITLE
Blurry Popover Text

### ISSUE THREAD

**Issue by jibberishclient** [palantir/blueprint#4074] opened 2020-04-20 18:18 UTC
![image](https://user-images.githubusercontent.com/11995299/79785353-bace8200-8311-11ea-8160-ad139bc51d70.png)

I'm running on Windows 10, latest Chrome and for some reason the popover text is very blurry on all popover based components (select, overflow menu, popover itself, etc). Is there a way to correct this behavior?

**Comment by adidahiya** [comment] 2020-04-20 19:23
duplicate of #394

**Closed by adidahiya** 2020-04-20 19:23 UTC
