### ISSUE TITLE
Date range bug around December 2016

### ISSUE THREAD

**Issue by raiju** [palantir/blueprint#391] opened 2016-12-27 15:34 UTC
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: Chrome v55 & Firefox v50 on MacOs X 10.11.6

#### Steps to reproduce

1. Open http://blueprintjs.com/docs/#components.datetime.daterangepicker
2. Select December 2016 on the left part of the date range picker
3. Notice the right picker now displays January 1996

#### Expected behavior

The right picker displays January 2017

![image](https://cloud.githubusercontent.com/assets/806013/21502725/2baf012c-cc52-11e6-8638-a49408e39dc9.png)

**Comment by adidahiya** [comment] 2016-12-27 18:09
Looks like a duplicate of #289, which should've been fixed by #312? The expected behavior here is that December 2016 shows up on the right and you aren't able to advance past the max date.

**Comment by giladgray** [comment] 2016-12-28 23:40
This is not exactly a duplicate, the repro steps say to explicitly select December 2016. But it is another way of triggering the same issue, which we can't really do anything about as it's part of the `react-day-picker` implementation.

In the example component, January 2017 is past the `maxDate` so the calendar wraps to the `minDate`.

**Comment by gpbl** [comment] 2017-01-04 15:18
Hi people, I believe the header is wrong - it should say "January 2017" because that is the month being displayed (see https://github.com/gpbl/react-day-picker/issues/243#issuecomment-270256154).

**Closed** 2017-01-06 21:44 UTC
Labels: P2, Package: datetime, Type: bug
