### ISSUE TITLE
Issue changing month and day on dateinput in Internet Explorer 11

### ISSUE THREAD

**Issue by timothymcooley** [palantir/blueprint#2924] opened 2018-09-11 15:33 UTC
#### Environment

- __Package version(s)__: Initially found in 2.0.2 , reproducible in 3.0.0+
- __Browser and OS versions__: Internet Explorer 11 & Windows 10

#### Steps to reproduce
Reproducible on the example: https://blueprintjs.com/docs/#datetime/dateinput
1) Click on a dateinput textbox to open the popover
2) Note the day selected
2) Go back a previous month
3) Click on a different day than what is selected
4) Note the selected day isn't what you clicked, it's the original day minus one month.

Note:  You can change days within the same month

#### Actual behavior

Cannot change day and month at the same time using dateinput popover

#### Expected behavior

The day you clicked is actually selected

#### Possible solution

Unsure.  It looks like the onChange for the dateinput doesn't actually fire on the click after changing months.  I attempted to use the isUserChange boolean to prevent the changing month from firing the onChange but the issue persists.

**Comment by giladgray** [comment] 2018-09-14 21:50
@timothymcooley I cannot reproduce this on IE.

**Comment by knalinne** [comment] 2018-10-09 10:43
@timothymcooley Hello ! 
I have the same issue and tried to investigate it ! 

First of all, this is how I reproduce it: 

![2018-10-09 12 13 56](https://user-images.githubusercontent.com/5163782/46662869-d7d2b280-cbbc-11e8-8621-067cc0914487.gif)

I found out that, after a month change, this function 
https://github.com/palantir/blueprint/blob/3f910a8aac3b72a7b8d77e39967808432a57b42c/packages/datetime/src/datePicker.tsx#L223
is never called on IE.

When the month has changed, the popup is closed by a blur event.
https://github.com/palantir/blueprint/blob/ac38072b019a21bd6d1fc302180010711610363c/packages/datetime/src/dateInput.tsx#L167-L170

https://github.com/palantir/blueprint/blob/ac38072b019a21bd6d1fc302180010711610363c/packages/datetime/src/dateInput.tsx#L381-L390

There is a difference between Chrome and IE in the 'relatedTarget'.
It's null on IE and it's a dom element in Chrome.

On IE, as the relatedTarget is null, the popup is closed. 
I guess that the click event is not triggered and that's the reason why the date do not change.

On Chrome, the relatedTarget is not null, the 'else' part of the function is called and everything works.  

I don't really know how to fix this.
According to https://stackoverflow.com/questions/41298948/how-to-use-relatedtarget-or-equivalent-in-ie, it looks like the relatedTarget do not correctly works on blur events.

By simply removing the call to `this.handleClosePopover(); ` it seems to work, but I suppose it will break something, this code is probably here for something :-) 

I hope this will help you to fix this ! 
Is there something else I can do to help ?

**Comment by giladgray** [comment] 2018-10-09 18:54
@knalinne thank you for the detailed report! at least we know where to focus our efforts to address this now 👍

**Closed** 2019-04-09 20:28 UTC
Labels: Browser: IE, Type: bug, help wanted
