### ISSUE TITLE
OverflowList can crash page at >50 items

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#5043] opened 2021-11-29 22:37 UTC
#### Environment

- __Package version(s)__: core@4.0.0-beta.10
- __Operating System__: OSX
- __Browser name and version__: Chrome 96.0.4664.55

#### Code Sandbox

I didn't want to make an account so I pasted the code below.

#### Steps to reproduce

1. Create an `OverflowList` with 50 items that only fits a small number of those items (<5)

#### Actual behavior

Maximum call stack error from React due to too many recursive updates.

#### Expected behavior

No error.

#### Possible solution

Change overflow detection logic to not require so many updates, such as by using binary search instead of rendering once per item.

#### Example code:

```
import React from "react";
import { OverflowList } from "@blueprintjs/core";

import { Example } from "./Example";

const items = [
  "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa", "aaaaaaaa"
];
export const CoreExample: React.FC = () => {
  return (
    <Example header="Crash">
      <OverflowList
        items={items}
        visibleItemRenderer={(item) => item}
        overflowRenderer={() => <div>overflow</div>}
      />
    </Example>
  );
};

```

**Comment by adidahiya** [comment] 2021-11-30 15:31
Duplicate of https://github.com/palantir/blueprint/issues/3792, can you please add your relevant comments there?

**Closed as completed by adidahiya** 2021-11-30 15:31 UTC
Labels: Resolution: duplicate
