### ISSUE TITLE
showHotkeyDialog method?

### ISSUE THREAD

**Issue by yaronlavi** [palantir/blueprint#2062] opened 2018-02-01 07:36 UTC
### Bug report

- __Package version(s)__: 1.35.1
- __Browser and OS versions__: Win 10, Chrome latest

#### Steps to reproduce
When using hotkeys, blueprint beautifully attaches a ? hotkey, which display the hotkeys dialog. But what if I need to show the dialog programmatically, for example by a button or menuItem click?

There's a `setHotkeysDialogProps` to format the dialog, but not for showing it programatically and I think it will really be handy.

**Comment by adidahiya** [comment] 2018-02-01 15:33
A valid request. Duplicate of #1590.

**Closed by adidahiya** 2018-02-01 15:33 UTC
