### ISSUE TITLE
Date Range Picker minute input does not work correctly

### ISSUE THREAD

**Issue by nznexus** [palantir/blueprint#3595] opened 2019-06-13 03:31 UTC
since updating blueprintjs/datetime to 3.9.1 ive had this issue.

to recreate:
- go here https://blueprintjs.com/docs/#datetime/daterangepicker
- change Time Precision to minute
- with any date range, attempt to change the minute input on either start or end (hour works fine)
it will change 1 digit, then unfocus before the full input can be accepted.
ie. change 00:00 to 15:27:

![daterangepicker](https://user-images.githubusercontent.com/25314557/59401833-373e2d80-8df0-11e9-95e0-248599fee40a.PNG)

**Comment by devsnowy** [comment] 2019-06-13 03:46
Indeed, it happens to me too.

**Comment by adidahiya** [comment] 2019-06-13 21:34
this looks like a duplicate of #3581

**Closed by adidahiya** 2019-06-13 21:34 UTC
