### ISSUE TITLE
Blurred Font in Popup Menu

### ISSUE THREAD

**Issue by avkonst** [palantir/blueprint#2786] opened 2018-08-09 12:32 UTC
#### Environment

- __Package version(s)__: 3.0.1
- __Browser and OS versions__: Chrome, Windows 10

#### Question

I have noticed inconsistent rendering for Popup Menu font. See perfect sharp font rendering for the 'River Estuary' words and see the blurred font for the menu item. How can I fix it? What is causing it?

![image](https://user-images.githubusercontent.com/3971413/43899032-cc9d27a4-9c34-11e8-9f82-0292cfb4039a.png)

**Comment by avkonst** [comment] 2018-08-09 12:38
You can check the rendered version here online: https://wildwind.world/explore

The code I use for the menu bar is very simple:
```
<Navbar.Group align={Alignment.RIGHT}>
                    <Popover
                        content={
                            <LocalStateContext.Consumer>{localstate =>
                                <Observer>{() =>
                                    <UserMenu
                                        user={localstate.user}
                                        onLoginClick={() => props.history.push('/login')}
                                        onLogoutClick={() => props.history.push('/logout')}
                                    />
                                }</Observer>
                            }</LocalStateContext.Consumer>
                        }
                        position={Position.BOTTOM_RIGHT}
                    >
                        <Button minimal={true} icon={IconNames.USER} />
                    </Popover>
                </Navbar.Group>
```
where `UserMenu` is the following:
```
interface UserMenuProps {
    user?: UserState;
    onLoginClick: () => void;
    onLogoutClick: () => void;
}

const UserMenu = (props: UserMenuProps) => {
    const items: { text: string, onClick: () => void, icon?: IconName }[] = [];
    if (!props.user) {
        items.push({ icon: IconNames.LOG_IN, text: 'Sign in / Register', onClick: props.onLoginClick });
    } else {
        items.push({ icon: IconNames.LOG_OUT, text: 'Sign out', onClick: props.onLogoutClick });
    }
    return (
    <Menu>
        {items.map(i => <MenuItem key={i.text} icon={i.icon} text={i.text} onClick={i.onClick} />)}
    </Menu>);
};
```

**Comment by giladgray** [comment] 2018-08-09 18:41
duplicate of #394. see discussion there.

**Closed by giladgray** 2018-08-09 18:41 UTC
