### ISSUE TITLE
Can't use Dialog and Select together

### ISSUE THREAD

**Issue by b-ponomarenko** [palantir/blueprint#4430] opened 2020-11-19 14:41 UTC
### Environment

- "@blueprintjs/select": "^2.0.1", "@blueprintjs/select": "^2.0.1"
- __Operating System__: 
- __Browser name and version__: 

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1. 
1. 
1.

**Comment by adidahiya** [comment] 2020-11-19 16:51
Probably a duplicate of #3854, but please fill out the issue template next time.

**Closed as completed by adidahiya** 2020-11-19 16:51 UTC
