### ISSUE TITLE
Make Date Picker that supports month-level granularity

### ISSUE THREAD

**Issue by CalvinFernandez** [palantir/blueprint#1593] opened 2017-09-21 18:31 UTC
As far as I know, the date picker component only supports day-level granularity. For my use case, the-day-of month is fairly irrelevant -- I just choose the 1st of each month -- and I would like a date picker component that lets me visually select months rather than days. My current workaround is to just disable all days except the first for each month and let the user navigate between months with the header
![image](https://user-images.githubusercontent.com/2644420/30712141-0040d3bc-9ed9-11e7-8b69-0bda419570d4.png)

but I would really prefer my calendar to show selectable months similar to this admittedly terrible example that i found. 

![image](https://user-images.githubusercontent.com/2644420/30712254-671cd09a-9ed9-11e7-91dd-e4cfaa793f13.png)
[link](https://i1.wp.com/alexandrafloersch.areavoices.com/files/2015/12/12-Month-Resolution-Calendar-1.png
)

**Comment by adidahiya** [comment] 2017-09-22 18:19
Wouldn't this just be a Select with 12 options? Not sure we need a whole component for it.

**Comment by giladgray** [comment] 2017-09-27 23:47
yeah we've declined this request before... duplicate of #1280.

**Closed by giladgray** 2017-09-27 23:47 UTC
Labels: Package: datetime, Type: feature request

**Comment by Ancez** [comment] 2025-04-15 11:32
A select dropdown does not allow users to move between years without another dropdown.

I'd like to use a month picker, not a select dropdown. Is this possible?

https://react-lite-month-picker.dev/ - I dislike the idea of having to A. rely on another package, B. code it myself.
