### ISSUE TITLE
using arrows to adjust date with `closeOnSelection` closes the popover

### ISSUE THREAD

**Issue by moon1ock** [palantir/blueprint#6488] opened 2023-10-23 10:48 UTC
#### Steps to reproduce

https://blueprintjs.com/docs/#datetime2/date-range-input3

video attached below

#### Actual behavior

using arrows to adjust date with `closeOnSelect` closes

https://github.com/palantir/blueprint/assets/43008895/a0dd52f7-b9c8-4ed8-8d7a-6355fb698c87

 the select window

#### Expected behavior

using arrows should not constitute as "select" so they should not close the select window

**Comment by adidahiya** [comment] 2023-10-23 12:31
Duplicate of #3376 and #4738, related to #1988. Until those are solved, I recommend using `closeOnSelection={false}` if you have the time picker enabled.

**Closed as completed** 2023-10-23 12:32 UTC
Labels: Resolution: duplicate, Package: datetime
