### ISSUE TITLE
[Table] Double-click Resizing on multiple columns selected should individually resize

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1779] opened 2017-11-02 23:40 UTC
Consistent with Excel & Sheets behavior
![resizing](https://user-images.githubusercontent.com/24398123/32355553-96f74f64-bfec-11e7-917a-c2e27b6ec96e.gif)

**Comment by cmslewis** [comment] 2017-11-02 23:42
Dupe of #1115

**Closed by cmslewis** 2017-11-02 23:42 UTC
