### ISSUE TITLE
Maximum update depth exceeded in overflow list with lots of items

### ISSUE THREAD

**Issue by MalikBagwala** [palantir/blueprint#3901] opened 2019-12-20 06:18 UTC
#### Environment

- __Package version(s)__: @blueprintjs/core@3.18.1
- __Browser and OS versions__:  Chrome 79.039 @ Ubuntu 19.10 64 bit

#### Steps to reproduce

1. Have an `OverflowList` component that renderers more than 64 (in my case) objects within an array in the `overflowRenderer` function

#### Actual behavior

1. The overflow  `overflowRenderer` passes the entire array for every item in it.
[1], [1,2], [1,2,3] and so on

#### Possible solution
The function should be only called once with all the elements

**Note: **
I found that this throws an error when an array of more than 53 items is supplied to the `<OverFlowList/>` component

**Comment by MalikBagwala** [comment] 2019-12-28 11:48
@giladgray 
@adidahiya

**Comment by adidahiya** [comment] 2020-01-08 16:31
@MalikBagwala thanks for filing the issue, would you mind making a code sandbox that shows a minimal repro of the issue? open to PRs

**Comment by nrathi** [comment] 2020-06-17 15:47
This seems like a duplicate of https://github.com/palantir/blueprint/issues/3792.

**Comment by adidahiya** [comment] 2020-06-17 16:39
closing in favor of #3792, which has more info

**Closed by adidahiya** 2020-06-17 16:39 UTC
Labels: P2, Package: core, Type: bug, help wanted
