### ISSUE TITLE
Icons inside Menu component does not have intent applied

### ISSUE THREAD

**Issue by jacekjagiello** [palantir/blueprint#3593] opened 2019-06-12 19:46 UTC
#### Environment

- __Package version(s)__: 3.15.1
- __Browser and OS versions__: probably all

#### Actual behavior
Similar to #3042, but affecting `Menu` component, `Icon`s passed to `MenuItem` components does not have intent color applied

#### Expected behavior
Intent colors should be applied

#### Possible solution
Similar ro #3355 , I'll do PR soon.

Does anyone have other components in mind, that may have a similar issue?

**Comment by adidahiya** [comment] 2020-06-23 17:44
`MenuItem` supports intent, and I'm not convinced that the icon needs its own special color unique from the containing item. Closing as "by design", similar to https://github.com/palantir/blueprint/pull/3597#issuecomment-588750035

**Closed by adidahiya** 2020-06-23 17:44 UTC
