### ISSUE TITLE
Popover2 Regression: ContextMenu2 scrolls to top when context menu is opened in Chrome and Firefox

### ISSUE THREAD

**Issue by mormahr** [palantir/blueprint#4979] opened 2021-10-22 01:34 UTC
#### Environment

- __Package version(s)__: @blueprintjs/core@3.51.1, @blueprintjs/popover2@0.12.1
- __Operating System__: macOS Big Sur 11.6 (20G165)
- __Browser name and version__: Chrome 95.0.4638.54 (arm64), Firefox 93.0, _Safari 15.0 (16612.1.29.41.4, 16612) [Safari still works]_

#### Code Sandbox

Link to a minimal repro: 

https://codesandbox.io/s/blueprint-sandbox-forked-sk3n3 (<- _not_ working with @blueprintjs/popover2@0.12.1)
https://codesandbox.io/s/blueprint-sandbox-forked-n4ck3 (<- working with @blueprintjs/popover2@0.12.0)

#### Steps to reproduce

1. Use current Firefox or Chrome (see versions above), Safari works as expected
2. Make browser window small enough that you have to scroll down to the context menu trigger
3. Right-click to open the context menu

#### Actual behavior

The viewport will have scrolled up to the top.

#### Expected behavior

The viewport stays as it is and displays the context menu.

#### Possible solution

The regression was introduced between @blueprintjs/popover2@0.12.0 and @blueprintjs/popover2@0.12.1.
Looking at the commits/diff of popover2 between the releases, maybe it's related to the changes of `shouldReturnFocusOnClose`? Though the only changed code I saw was `handleTargetBlur` which (afaik) isn't called during the reproduction. 

https://user-images.githubusercontent.com/7482056/138379066-00f9d880-b9ba-4cb1-9ff2-ab0d1c55c4e5.mov

**Comment by adidahiya** [comment] 2021-10-22 14:36
essentially a duplicate of #4981

**Closed as completed by adidahiya** 2021-10-22 14:36 UTC
Labels: Type: bug, Resolution: duplicate, P1, Package: popover2
