### ISSUE TITLE
FormGroup not handling whitespace properly

### ISSUE THREAD

**Issue by marvinsum** [palantir/blueprint#2451] opened 2018-05-02 20:48 UTC
### Bug report

- __Package version(s)__: 1.36.1
- __Browser and OS versions__: Chrome 66.0.3359.117, MacOS 10.13.3

It seems like the `<FormGroup>` component isn't handling whitespace correctly. On lines 64 and 65 of `formGroup.tsx`, the `{label}` and `{this.maybeRenderRequiredLabel()}` don't have any whitespace once it's compiled into html. This makes the `label` and optional `requiredLabel` render next to each other.

https://github.com/palantir/blueprint/blob/179bdeffff186319cab0adf53596dcdf45a7f04c/packages/core/src/components/forms/formGroup.tsx#L64-L65

https://stackoverflow.com/questions/32686728/how-to-avoid-jsx-component-from-condensing-when-react-js-rendering-it

#### Steps to reproduce

1. Create a new `<FormGroup />`
2. Add `label` and `requiredLabel` props to `<FormGroup />`
3. View in browser

#### Actual behavior

No space between `label` and `requiredLabel`.

#### Expected behavior

One or more spaces between `label` and `requiredLabel`.

**Comment by giladgray** [comment] 2018-05-02 21:54
duplicate of #2416

**Closed by giladgray** 2018-05-02 21:54 UTC
