### ISSUE TITLE
ContextMenu Positioning Incorrect

### ISSUE THREAD

**Issue by dannmartens** [palantir/blueprint#6526] opened 2023-11-08 08:24 UTC
#### Environment

    "@blueprintjs/core": "^5.6.0",
    "@blueprintjs/datetime2": "^2.2.3",
    "@blueprintjs/docs-theme": "^5.1.1",
    "@blueprintjs/icons": "^5.3.0",
    "@blueprintjs/select": "^5.0.17",
    "@blueprintjs/timezone": "^4.5.43",
    "@reduxjs/toolkit": "^1.9.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.17.0",

#### Question

In my application, all the context menu pop-ups position themselves in upper left corner.
I copied the Tree example, which has a context menu, into my project and that context menu pop-up has the same issue.

![image](https://github.com/palantir/blueprint/assets/263133/13bfb26b-a0b4-4f4d-a575-df4820846eb9)

Is there any way I can investigate what is causing this? Your help would be appreciated!

**Comment by adidahiya** [comment] 2023-11-08 12:43
duplicate of https://github.com/palantir/blueprint/issues/5503

**Closed as completed by adidahiya** 2023-11-08 12:43 UTC
Labels: Resolution: duplicate

**Comment by dannmartens** [comment] 2023-11-08 18:01
@adidahiya Thanks! I searched the issues for this, but apparently I did not use the right keywords!
