### ISSUE TITLE
Three shaking for blueprint v2.

### ISSUE THREAD

**Issue by johnunclesam** [palantir/blueprint#2387] opened 2018-04-12 22:26 UTC
### Bug report

- __Package version(s)__: 2 latest

#### Steps to reproduce

Just

`import { Icon } from "@blueprintjs/core";`

in my react app and I got this:

![image](https://user-images.githubusercontent.com/21275217/38707267-031a626a-3eb1-11e8-957d-84463a54974c.png)

Why all this components from Blueprint?

I can understand icons (and something is happening: https://github.com/palantir/blueprint/pull/2356), but not all that components which I don't need...

**107.46 KB useless...**

How to remove that code from my project ? Three-shaking?

**Comment by giladgray** [comment] 2018-04-12 22:43
duplicate of #2193. PR in progress: #2356. this will ship in 3.0, coming in a few weeks.

**Comment by giladgray** [comment] 2018-04-12 22:44
@johnunclesam yes, tree shaking is how you remove dead code: https://webpack.js.org/guides/tree-shaking/

**Closed by giladgray** 2018-04-12 22:43 UTC

**Comment by johnunclesam** [comment] 2018-04-12 23:02
Not just for the icons, right?

PR also for all the core components?

Or still all 100 KB for just one single component?

**Comment by johnunclesam** [comment] 2018-04-16 11:57
@giladgray just for the icons or for single component also?

**Comment by johnunclesam** [comment] 2018-04-19 15:01
Dear @giladgray you said me to go here: https://github.com/palantir/blueprint/issues/2042, but what I don't understand is how to use just one single component (maybe also using `import X from "@blueprintjs/core/src..."`) in a new, latest `create-react-app`.

Is this possible today?
