### ISSUE TITLE
Icons add 430 kB, do not tree-shake

### ISSUE THREAD

**Issue by hyperknot** [palantir/blueprint#5102] opened 2022-01-19 09:20 UTC
#### Environment

- __Package version(s)__: 3.x and 4.x beta, same behaviour
- __Operating System__: macOS, yarn v1

#### Steps to reproduce

1. `yarn create react-app`
1. `yarn add @blueprintjs/core@4.x` // select latest
1. `yarn add source-map-explorer`
2. add:
```
import { Button } from "@blueprintjs/core";
<Button intent="success" text="button content"/>
```
3. `yarn source-map-explorer build/**/*.js`

#### Actual behavior

For a simple 1 line button example, we ended up with 430 kB of icons included. This is the same in 3.x and 4.x beta.

![image](https://user-images.githubusercontent.com/494223/150100826-4a8175f9-3717-4b5b-bbf8-245a937f6f37.png)

#### Expected behavior

Bundle only the used icons. [React-icons](https://react-icons.github.io/react-icons/) does this, even though it's a huge package, at the bundle it only shows up as a few kB's of icons.

#### Possible solution

Implement tree-shaking in 4.x, like react-icons does.

**Comment by adidahiya** [comment] 2022-01-19 13:26
duplicate of https://github.com/palantir/blueprint/issues/2193, will be fixed in v5.x

**Closed as completed by adidahiya** 2022-01-19 13:26 UTC
Labels: Resolution: duplicate, Package: icons
