### ISSUE TITLE
Has anyone got Blueprint working with Next.js 13 app dir/RSC?

### ISSUE THREAD

**Issue by switz** [palantir/blueprint#5854] opened 2023-01-19 02:09 UTC
#### Environment

- __Package version(s)__: 4.14.1
- __Browser and OS versions__: Mac Stable, Firefox Stable

#### Question

Has anyone been able to get Blueprint working with next.js 13 and the app dir/edge runtime? I can get mine rendering in dev mode, but it spouts out a ton of warnings (due to React-DOM exports) and then fails to build in production.

To add: this is on the edge runtime, not in nodejs. You can opt into the edge runtime at `{ runtime: 'edge' }` in your next.js config.

In dev:

```
warn  - ../../node_modules/@blueprintjs/core/lib/esm/components/context-menu/contextMenu.js
Attempted import error: 'render' is not exported from 'react-dom' (imported as 'ReactDOM').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/context-menu/contextMenu.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/context-menu/contextMenu.js
Attempted import error: 'unmountComponentAtNode' is not exported from 'react-dom' (imported as 'ReactDOM').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/context-menu/contextMenu.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/context-menu/contextMenuTarget.js
Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'ReactDOM').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/context-menu/contextMenuTarget.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog.js
Attempted import error: 'render' is not exported from 'react-dom' (imported as 'ReactDOM').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog.js
../../node_modules/@blueprintjs/core/lib/esm/components/hotkeys/index.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog.js
Attempted import error: 'unmountComponentAtNode' is not exported from 'react-dom' (imported as 'ReactDOM').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog.js
../../node_modules/@blueprintjs/core/lib/esm/components/hotkeys/index.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/overlay/overlay.js
Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'findDOMNode').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/overlay/overlay.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/resize-sensor/resizeSensor.js
Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'findDOMNode').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/resize-sensor/resizeSensor.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx

../../node_modules/@blueprintjs/core/lib/esm/components/toast/toaster.js
Attempted import error: 'render' is not exported from 'react-dom' (imported as 'ReactDOM').

Import trace for requested module:
../../node_modules/@blueprintjs/core/lib/esm/components/toast/toaster.js
../../node_modules/@blueprintjs/core/lib/esm/components/index.js
../../node_modules/@blueprintjs/core/lib/esm/index.js
./src/modules/home/components/MyMatches.tsx
```

I'm not even importing the offending components, but since I'm using the default import I suppose they're getting compiled along.

And then when building in prod, I get this error:

```
info  - Skipping linting
info  - Checking validity of types
info  - Collecting page data ..TypeError: Cannot read properties of undefined (reading 'files')
```

Any insight would be helpful.

**Comment by adidahiya** [comment] 2023-01-19 14:52
Are you using React 18? How are you using the default import? We don't `export default` anywhere as top-level public API. If it's a synthetic default, that's not recommended for any Blueprint libraries. You should use named imports to get just the components you need.

**Comment by switz** [comment] 2023-01-19 19:20
I'm importing components from the top level api, not synthetic defaults afaik:

e.g. `import { Button, Intent } from '@blueprintjs/core';`

and

`import { Classes, Icon, Intent, NonIdealState } from '@blueprintjs/core';`

**Comment by adidahiya** [comment] 2023-01-20 16:36
Hmm, now that I look more closely, ESM tree-shaking won't work properly because of this line: https://github.com/palantir/blueprint/blob/6cfa0d407e0232573e1d6fad1716ec2092ac96d4/packages/core/src/components/index.ts#L19

We'll have to refactor that export to make it tree-shakable. Until then, can you apply some kind of webpack override to never load the folder `@blueprintjs/core/lib/esm/components/context-menu/`?

**Comment by switz** [comment] 2023-01-20 18:19
> Hmm, now that I look more closely, ESM tree-shaking won't work properly because of this line:
> 
> https://github.com/palantir/blueprint/blob/6cfa0d407e0232573e1d6fad1716ec2092ac96d4/packages/core/src/components/index.ts#L19
> 
> We'll have to refactor that export to make it tree-shakable. Until then, can you apply some kind of webpack override to never load the folder `@blueprintjs/core/lib/esm/components/context-menu/`?

I'll give it a shot, most likely next week. This would be really nice to fix as its the only thing stopping me from using the edge runtime. Thanks for looking into it!

**Comment by switz** [comment] 2023-01-20 20:03
do all exports suffer from this problem? would it be possible to convert all `export *` to `export { default as Foo, OtherModule, OtherModule2 }` and improve dead code elimination? my biggest issue with blueprint is bundle size + lack of tree shaking, to the point where I've deeply considered migrating off of it.

edit: ran a quick test and doesn't seem like that would change a whole lot w/r/t bundle size
![Screenshot 2023-01-20 at 15 08 56](https://user-images.githubusercontent.com/990166/213796648-e4e6fffc-bee2-4852-8bb9-63c7e1eab254.png)


![image](https://user-images.githubusercontent.com/990166/213798267-47db4877-bd14-4006-936d-31a46e2cf8ed.png)

**Comment by adidahiya** [comment] 2023-01-23 15:08
> do all exports suffer from this problem? would it be possible to convert all export * to export { default as Foo, OtherModule, OtherModule2 } and improve dead code elimination?

I think this would be possible to do for the v5.0 release, I'll keep it on my radar...

**Comment by S0urcemaster** [comment] 2023-08-16 12:22
Hi,
I'm doing a project with bp5 and nextjs app/ dir structure.
bp5 components don't work in any folder below app/.
Components load and work correctly in any file directy under app/ but not in subdirectories.
Within these I'm getting this error (tried with Card and Section):

Server Error

TypeError: Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Module.__extends
..\node_modules\.pnpm\tslib@2.5.3\node_modules\tslib\tslib.es6.mjs (26:12)
__extends
..\node_modules\.pnpm\@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0\node_modules\@blueprintjs\core\lib\cjs\common\abstractComponent.js (28:12)
React
..\node_modules\.pnpm\@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0\node_modules\@blueprintjs\core\lib\cjs\common\abstractComponent.js (107:2)
(sc_server)/../../node_modules/.pnpm/@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0/node_modules/@blueprintjs/core/lib/cjs/common/abstractComponent.js
file:/C:/Users/sebas/IdeaProjects/digicraft/apps/digicraft3/.next/server/app/news/page.js (1907:1)
__webpack_require__
file:/C:/Users/sebas/IdeaProjects/digicraft/apps/digicraft3/.next/server/webpack-runtime.js (33:43)
require
..\node_modules\.pnpm\@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0\node_modules\@blueprintjs\core\lib\cjs\common\index.js (22:26)
(sc_server)/../../node_modules/.pnpm/@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0/node_modules/@blueprintjs/core/lib/cjs/common/index.js
file:/C:/Users/sebas/IdeaProjects/digicraft/apps/digicraft3/.next/server/app/news/page.js (1984:1)
__webpack_require__
file:/C:/Users/sebas/IdeaProjects/digicraft/apps/digicraft3/.next/server/webpack-runtime.js (33:43)
require
..\node_modules\.pnpm\@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0\node_modules\@blueprintjs\core\lib\cjs\index.js (22:21)
(sc_server)/../../node_modules/.pnpm/@blueprintjs+core@5.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0/node_modules/@blueprintjs/core/lib/cjs/index.js


I found this thread but didn't help me: [https://stackoverflow.com/questions/43176006/typeerror-class-extends-value-undefined-is-not-a-function-or-null](https://stackoverflow.com/questions/43176006/typeerror-class-extends-value-undefined-is-not-a-function-or-null)

**Comment by S0urcemaster** [comment] 2023-08-16 12:38
I'm using react 18.2.0 and next 13.4.6

**Comment by S0urcemaster** [comment] 2023-08-16 16:58
I found it:
Missing `'use client'` in the using component.

**Comment by gabrielmcreynolds** [comment] 2023-09-28 18:48
> I found it: Missing `'use client'` in the using component.

I've run into this issue as well; however, there are many cases where we would want to use blueprint.js components in server components. #6100 Does not fix this problem. Is there a timeline to win this will be fixed?

**Comment by adidahiya** [comment] 2023-09-29 14:55
Can anyone produce a working code sandbox repro of the problem? I'm not exactly sure where to start with this one. There are some Blueprint components which use layout effects which seem to be unfriendly with React server components. That's one (related, but different) issue.

There seems to be another issue referenced in this thread that has more to do with build tooling rather than runtime behavior.

Maybe it's our usage of `import * as React` and `import * as ReactDOM`? We can't move away from that syntax until we enable `allowSyntheticDefaultImports`, which I hope to do at some point, but it will be a breaking change.

I'm hoping that someone with more Next.js experience can contribute a fix for this issue, it's open for PRs.

**Comment by adidahiya** [comment] 2024-01-09 16:00
I think this is essentially a duplicate of #6263, closing in favor of that issue.

**Closed as completed by adidahiya** 2024-01-09 16:00 UTC
Labels: Type: bug, Type: question, Domain: API, help wanted
