### ISSUE TITLE
Opened popover continues to scroll top the page

### ISSUE THREAD

**Issue by alearcy** [palantir/blueprint#357] opened 2016-12-12 22:24 UTC
### Bug report

- __Package version(s)__: 1.3.1
- __Browser and OS versions__: Chrome 55.0.2883.87, MacOs Sierra

#### Steps to reproduce

![scroll top when popover is open](https://cloud.githubusercontent.com/assets/5402295/21119252/1297fa5e-c0c2-11e6-8e45-fae79ecd1d95.gif)

**Comment by llorca** [comment] 2016-12-13 01:24
Can't repro in the docs (same version/browser): http://blueprintjs.com/docs/#components.popover

Can you provide more info on your setup/markup/styles?

**Comment by alearcy** [comment] 2016-12-13 09:19
If you try with a popover already in top page position the problem doesn't exists (like docs example). But if you try with a popover at the middle of a scrolled page, it scrolls to top. Show this new gif:

![scroll top when popover is open 2](https://cloud.githubusercontent.com/assets/5402295/21134301/779ba21a-c11d-11e6-89c1-51a9f8335f99.gif)


I'm using vanilla blueprintjs with vanilla bootstrap grid system.

Thanks ;-)

**Comment by giladgray** [comment] 2016-12-13 17:23
Sorry I am also not able to reproduce this. I have tried scrolling the page (very easy to do on [DateInput](http://blueprintjs.com/docs/#components.datetime.dateinput) because the page has to be scrolled). Are you _sure_ you're serving the latest code?

**Comment by alearcy** [comment] 2016-12-13 20:44
Yep @giladgray I have the latest 1.3.1 version.
The only strange thing I'm seeing is a data-tether-id styled with top: 0, left: 0; position: absolute that appears when Popover is open.
![schermata 2016-12-13 alle 21 40 50](https://cloud.githubusercontent.com/assets/5402295/21158388/5709f2e4-c17d-11e6-98a3-2561d3f85d7d.png)

**Comment by giladgray** [comment] 2016-12-13 20:50
Have you updated Tether to 1.4.0? It's expressed in package.json now.

**Comment by alearcy** [comment] 2016-12-13 20:55
Yep
![schermata 2016-12-13 alle 21 54 52](https://cloud.githubusercontent.com/assets/5402295/21158775/de317368-c17e-11e6-846f-82cca496dc5e.png)

**Comment by giladgray** [comment] 2017-01-06 19:04
@alearcy that `data-tether-id` is expected behavior of Tether, definitely not a bug. i'm going to close this issue as it doesn't seem like there are any real problems here. feel free to reopen if that is incorrect.

**Closed by giladgray** 2017-01-06 19:04 UTC
Labels: Status: needs more info
