### ISSUE TITLE
NumericInput fill prop doesn't work

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#4213] opened 2020-07-07 19:31 UTC
discovered while testing https://github.com/palantir/blueprint/pull/4211

#### Environment

- __Package version(s)__: develop & 3.29.0
- __Operating System__: macOS
- __Browser name and version__: Firefox

#### Steps to reproduce

1. Enable fill option in NumericInput docs

#### Actual behavior

<img width="814" alt="image" src="https://user-images.githubusercontent.com/723999/86832940-d6227100-c066-11ea-8d90-34080a33ad8b.png">

#### Expected behavior

control group should be full width

**Comment by ejose19** [comment] 2020-07-07 23:36
@adidahiya Made a fix for this and a side effect caused by AnchorButton, please take a look #4214

**Comment by adidahiya** [comment] 2020-09-09 14:16
This bug is back, regression happened somewhere

**Comment by ejose19** [comment] 2020-09-09 16:50
@adidahiya Well, if you check the control group it works because it's using an external style applied to make it work. When I proposed changing the scss you replied this: https://github.com/palantir/blueprint/pull/4214#discussion_r452591445 and the change got removed, so this was never "fixed" in practice.

If you want to fix for docs only, then just copying the same logic into numeric input works. However I think it's better to update the class to avoid doing additional logic, adding either ```width: 100%``` or ```flex-grow: 1``` works, so let me know which one do you prefer and I can create the PR.

**Closed as completed** 2020-09-10 14:13 UTC
Labels: Type: bug, P2, help wanted, Package: core
