### ISSUE TITLE
[Table] Don't toggle selection when clicking on column menu target

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1266] opened 2017-06-22 17:38 UTC
### Bug report

- __Package version(s)__: v1.20.0
- __Browser and OS versions__: Chrome 59 on Mac OS X Sierra

#### Steps to reproduce

1. Enable column menus and `FULL_COLUMNS` selection mode.
1. Click on a column menu caret.

#### Actual behavior

Selected state toggles.

![menu-selection](https://user-images.githubusercontent.com/443450/27447731-01ec34ca-5737-11e7-88eb-e26e3d1dc3c3.gif)

#### Expected behavior

Selected state does not toggle (or maybe it toggles to selected, but not to deselected thereafter?).

**Comment by cmslewis** [comment] 2017-06-22 17:39
@llorca thoughts?

**Comment by llorca** [comment] 2017-06-22 17:51
@cmslewis I agree with the expected behavior you describe. IMO this isn't about column headers or menu carts specifically, it's a broader concern about non-standard selection toggle. Dupe of https://github.com/palantir/blueprint/issues/1073?

**Comment by cmslewis** [comment] 2017-06-27 20:45
@llorca I'm happy to fold this into #1073.

**Closed** 2017-06-27 20:46 UTC
Labels: Package: table, Type: bug
