### ISSUE TITLE
DateInput issue regarding month/year dropdowns in Internet Explorer 11

### ISSUE THREAD

**Issue by marcandreh** [palantir/blueprint#3172] opened 2018-11-21 09:56 UTC
#### Environment

- __Package version(s)__: DateTime 3.4.0 (Core 3.9.0)
- __Browser and OS versions__: Internet Explorer 11.285.17134.0 and Windows 10 Pro, Version 1803, Build 17134.286

#### Steps to reproduce

1. Click on a DateInput textbox to open the popover
1. Click on the month dropdown and select a different month
1. Click on the year dropdown

![bp-dateinput-bug](https://user-images.githubusercontent.com/22033866/48833592-0034fb80-ed7c-11e8-813a-cdc17d9b93eb.gif)

Can also be reproduced by using the year dropdown first and then clicking on the month dropdown.

#### Actual behavior
The DateInput popover closes unexpectedly.

#### Expected behavior
The DateInput popover stays open while opening the month/year dropdown.

#### Possible solution
Unsure. Could be linked to a similar problem in #2924.

**Comment by giladgray** [comment] 2018-11-27 22:37
duplicate of #2924. discuss there.

**Closed by giladgray** 2018-11-27 22:37 UTC
