### ISSUE TITLE
TypeError: moment is not a function

### ISSUE THREAD

**Issue by zsherman** [palantir/blueprint#959] opened 2017-04-06 21:47 UTC
It seems that moment@2.14 exports moment as a function by default but it's being imported with the syntax `import * as moment from 'moment'`, yet this file https://github.com/palantir/blueprint/blob/master/packages/datetime/src/common/dateUtils.ts #calls `moment` as a function in multiple places, which leads to this error. Has anyone seen this or been able to reproduce? Might be missing something here...

Also obligatory shoutout for the awesome lib, thanks for all your hard work.

### Bug report

- __Package version(s)__: 1.14
- __Browser and OS versions__: OSX El Capitan

#### Steps to reproduce

1. Import `DateRangeInput` and pass in valid dates

#### Actual behavior

`TypeError: moment is not a function` is thrown

#### Expected behavior

Should not throw an error.

**Comment by giladgray** [comment] 2017-04-06 22:32
@zsherman hmm nothing seems to have changed in `moment` itself--usage has always been as a function. are you sure it's installed and being imported correctly in your application?

**Comment by adidahiya** [comment] 2017-04-06 22:33
Do you mean to say that moment is exported as a default export (`export default moment`)? That gets compiled down to a simple `module.exports` in commonJS. The source here suggests that a function _is_ the module export: https://unpkg.com/moment@2.14.1/moment.js

Anything interesting about your build system that may cause moment to not be loaded or bundled correctly?

**Comment by zsherman** [comment] 2017-04-06 22:54
Hmm don't think I'm doing anything special, when I inspect moment in the chrome debugger I'm seeing that moment is indeed an object, not a function:

![screenshot 2017-04-06 18 54 27](https://cloud.githubusercontent.com/assets/1152279/24778790/7ed65bec-1afa-11e7-846a-73a949a84c20.png)

**Comment by zsherman** [comment] 2017-04-06 22:58
For what it's worth, I have no issues with the `DayPicker`, only with anything that relies on `dateInput`.

**Comment by zsherman** [comment] 2017-04-06 23:13
My guess is it's the way it's being imported here https://github.com/palantir/blueprint/blob/master/packages/datetime/src/common/dateUtils.ts#L8, which I thought pulls the export into a new object, which I can reproduce locally. Importing like `import moment from 'moment'` pulls in a function.

**Comment by adidahiya** [comment] 2017-04-07 07:17
> which I thought pulls the export into a new object

not quite; `import * as moment` assigns `module.exports` of the entry point of the package to the `moment` symbol in the scope. `module.exports` is often an object, but it can be any value and in the case of the moment library it is a function.

can you provide a minimal repro of your error? what build system or module loader are you using? where exactly are you stepping through code to get `moment` to show up like that in the chrome debugger? I don't think there's anything wrong with the way `@blueprintjs/datetime` imports moment; you'll notice that [most TS code on github does it this way](https://github.com/search?q=import+%2A+as+moment&type=Code&utf8=%E2%9C%93).

**Comment by zsherman** [comment] 2017-04-07 14:10
thanks @adidahiya, so here's the webpack config my app is based off of https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json, I was able to run into the same error with a fresh install so I'm suspicious that it's something to do with the way modules are being imported there.

In order to inspect the value of moment I'm just placing a breakpoint at the line where it's failing and added adding a watcher here https://www.dropbox.com/s/jbv22lp0bpaxbxh/Screenshot%202017-04-07%2010.10.03.png?dl=0.

**Comment by zsherman** [comment] 2017-04-07 14:16
@adidahiya here's an example repo with a fresh install of blueprint, if you installs deps and load up the homepage you should see the error https://github.com/zsherman/blueprint-test

**Comment by tannerlinsley** [comment] 2017-04-07 17:21
I can confirm this. When importing with * syntax, I indeed receive an object with moment as a key. This is in line with how moment is being exported as "export default moment" here: https://github.com/moment/moment/blob/develop/src/moment.js#L82

When importing as "import moment from 'moment'" only then do I receive a function.

**Comment by tannerlinsley** [comment] 2017-04-07 17:25
Also worth noting that moments module.exports is not a function, but as per es6 module export spec, it is an object with moment assigned to the default key.

**Comment by giladgray** [comment] 2017-04-07 17:43
this seems like an actual issue with moment & typescript: https://github.com/moment/moment/issues/3650

they clearly use ES6 `export default` in the main file, but at the same time our `import * as moment` has worked swimmingly for _months_. seems to be an issue related to how you run the code in the browser.

**Comment by seansfkelley** [comment] 2017-04-19 17:02
The [source of moment uses `export default`](https://github.com/moment/moment/blob/develop/src/moment.js#L82), but [the transpiled code ends up as `module.exports = ...`](https://github.com/moment/moment/blob/develop/moment.js#L8), meaning that [the obnoxious `export = ...` syntax in the typings](https://github.com/moment/moment/blob/develop/moment.d.ts#L712) is correct, despite what the original source would have you believe, and `import * as moment from 'moment'` is correct as long as you aren't using `allowSyntheticDefaultImports`.

**Comment by opavader** [comment] 2017-04-27 12:00
having the exact same issues with `datetime@1.14.0` & `moment@2.18.1`.
Any possibles workaround or idea for temporary fixing this?

**Comment by seansfkelley** [comment] 2017-04-27 18:33
The root cause is probably an unfortunate combination of compiler flags, possibly across languages/compilers, causing a disconnect between what you think you're writing and what is actually coming out the other end.

@opavader / @zsherman are you using Typescript or plain Javascript? Babel also does some weird stuff around these "synthetic defaults" (which I think causes more problems than it solves), so I'd poke around the transpiled output of your project, Blueprint and your version of moment to see which ones are in agreement and which are importing the wrong thing.

**Comment by bitIO** [comment] 2017-05-08 15:33
I'm also using `reactboilerplate` and I have the same issue. Fixed adding the package `moment-es6`.

**Comment by opavader** [comment] 2017-05-10 06:25
I@seansfkelley Using typescript. I downgraded my `moment` version to 2.14.1 but even then same error. Setting `allowSyntheticDefaultImports` to `false` will break other packages in use. My compiler options in `tsconfig.json` is

``` json
"compilerOptions": {
        "noUnusedParameters": true,
        "noUnusedLocals": true,
        "skipLibCheck": true,
        "noEmit": true,
        "target": "es6",
        "module": "commonjs",
        "noImplicitAny": false,
        "sourceMap": true,
        "inlineSourceMap": false,
        "inlineSources": false,
        "preserveConstEnums": true,
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "jsx": "preserve",
        "lib": [
            "dom",
            "es5",
            "es6",
            "es7",
            "es2017.object"
        ],
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./",
        "paths": {
            "ArchApp/*": [
                "src/*"
            ]
        }
    },
```

**Comment by wshaver** [comment] 2017-10-11 22:17
Super hacky, but this is how I solved my problem with moment/typescript/webpack:

```
let moment = require("moment");
if ("default" in moment) {
    moment = moment["default"];
}

```

**Comment by opavader** [comment] 2017-10-11 23:40
Yeah, I did the same. 
Wierd that even https://github.com/moment/moment-timezone/issues/449 has the same issue.

**Comment by AlejandroMoran** [comment] 2017-12-14 16:20
@wshaver Your solution works for me, I had extra problems because I was creating a library with ng-packagr and it works now. Thanks.

**Comment by monikaja** [comment] 2018-03-16 09:22
Word "require" makes my ionic app execution fail (ts error), so I've changed @wshaver solution for this:

`import * as moment from "moment";
let Moment;
if ("default" in moment) {
  Moment = moment["default"];
}`

**Comment by giladgray** [comment] 2018-03-16 19:09
2.0.0-rc.3 now uses Typescript's new `esModuleInterop` and the latest version of `tslib`, which should fix any moment import issues. 

additionally, `datetime@2.0` no longer depends on `moment` so that should further solve this problem. (`timezone` still uses `moment-timezone` though)

**Closed by giladgray** 2018-03-16 19:09 UTC
Labels: Package: datetime, Type: question

**Comment by minato-namikaze** [comment] 2018-09-28 15:28
@seansfkelley thanks. You saved my weekend :-)

**Comment by angelarted** [comment] 2019-02-19 09:53
So definitely, to get moment work as a function, if you are using ES6 and babel, you must import it in this way:
`import moment from 'moment'` 
and not, as written in the documentation
`import * as moment from 'moment'`

**Comment by GeorgeWL** [comment] 2019-04-08 10:48
This isn't resolved though really, as tests should be agnostic and not force you to have to change how you import into modules for them to work. 

Can we re-open this please?

**Comment by cherucole** [comment] 2019-12-07 10:15
> import moment from 'moment'

the solution **import moment from 'moment'** worked for me

**Comment by hlawuleka** [comment] 2020-02-24 08:59
> My guess is it's the way it's being imported here https://github.com/palantir/blueprint/blob/master/packages/datetime/src/common/dateUtils.ts#L8, which I thought pulls the export into a new object, which I can reproduce locally. Importing like `import moment from 'moment'` pulls in a function.

Consider `import moment, * as MyObjectMoment from 'moment';`

**Comment by estrings** [comment] 2020-05-04 10:51
> So definitely, to get moment work as a function, if you are using ES6 and babel, you must import it in this way:
> `import moment from 'moment'`
> and not, as written in the documentation
> `import * as moment from 'moment'`

you are doing well dear

**Comment by GeorgeWL** [comment] 2020-05-04 12:48
This isn't resolved though really, as tests should be agnostic and not force you to have to change how you import into modules for them to work.

Can we re-open this please?

**Comment by IhorVimmi** [comment] 2020-05-04 14:51
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

**Comment by Ritin** [comment] 2020-05-04 15:21
import * as temp from 'moment';
const moment = temp["default"];

**Comment by GeorgeWL** [comment] 2020-05-04 15:29
right?

**Comment by IhorVimmi** [comment] 2020-05-04 15:31
import moment from 'moment'; for me

This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

**Comment by adidahiya** [comment] 2020-05-04 15:31
> This isn't resolved though really, as tests should be agnostic and not force you to have to change how you import into modules for them to work.

Which part of this issue is specific to tests?

This is an old issue, but @seansfkelley's comment https://github.com/palantir/blueprint/issues/959#issuecomment-295346290 is still essentially correct (albeit with updated code links: [moment `default` export source](https://github.com/moment/moment/blob/1872bb22ff6cd19c56e7dc30c5765489d48e65f1/src/moment.js#L93), [moment transpiled export](https://github.com/moment/moment/blob/1872bb22ff6cd19c56e7dc30c5765489d48e65f1/moment.js#L8), [moment export type definition](https://github.com/moment/moment/blob/1872bb22ff6cd19c56e7dc30c5765489d48e65f1/moment.d.ts#L778)). So I don't think this requires a change in Blueprint. This issue can be resolved by tweaking your build tooling. If you can demonstrate a clear repro of a bug that warrants a change in Blueprint, please file a new issue and link to a repo and point out how the build system works (or breaks).

**Comment by zubairkhanshinwari** [comment] 2021-07-29 05:21
import * as moment from 'moment'

can not work for me still not working...................
