### ISSUE TITLE
Сannot change the minutes in the date and time selection window

### ISSUE THREAD

**Issue by joker63** [palantir/blueprint#3586] opened 2019-06-07 09:15 UTC
Сannot change the minutes in the date and time selection window.
version: 3.15.1

https://blueprintjs.com/docs/#datetime/dateinput
Date format: YYYY-MM-DD HH:mm:ss (moment)
Time precision: minute

**Comment by adidahiya** [comment] 2019-06-13 21:35
duplicate of #3581

**Closed by adidahiya** 2019-06-13 21:35 UTC
