### ISSUE TITLE
Tooltip rendered in wrong location

### ISSUE THREAD

**Issue by shravan2x** [palantir/blueprint#2359] opened 2018-04-04 06:24 UTC
### Bug report

- __Package version(s)__: 2.0.1
- __Browser and OS versions__: Chrome 65, Windows 10

#### Steps to reproduce

1. Place an element with a tooltip inside the `rightElement` of an input box like so:

```js
rightElement={
    <Tooltip content={'Lock this Drive'} isOpen={true}>
        <Button
            className={Classes.MINIMAL}
            intent={Intent.WARNING}
            icon={'unlock'}
        />
    </Tooltip>
}
```

#### Actual behavior

The tooltip is rendered in the top-left of the screen.

![image](https://user-images.githubusercontent.com/4096676/38291728-ac228ec6-37a6-11e8-9c6e-417a20808bf4.png)

#### Expected behavior

The tooltip should be on top of the lock icon in the input field.

This is a regression in 2.0.0.

**Comment by dmitruk** [comment] 2018-04-04 09:12
Use `npm install --save-dev popper.js@1.14.1` as a workaround.

**Comment by shravan2x** [comment] 2018-04-04 11:46
@dmitruk Oh is this a known issue?

**Comment by dmitruk** [comment] 2018-04-04 11:48
No)
But I also ran into this problem yesterday.

**Comment by thegecko** [comment] 2018-04-04 12:32
Can confirm fixing popper.js @ 1.14.1 fixes the issue.

**Comment by llorca** [comment] 2018-04-04 17:06
Dupe of https://github.com/palantir/blueprint/issues/2352

**Closed by llorca** 2018-04-04 17:06 UTC
Labels: Package: core, Resolution: external, Type: bug
