### ISSUE TITLE
Use scss in webpack project

### ISSUE THREAD

**Issue by 0vvland** [palantir/blueprint#3059] opened 2018-10-21 17:52 UTC
#### Environment

- __Package version(s)__: 3.6.1
- __Browser and OS versions__: any

#### Question
I try to restyle Blueprint. I import styles like this:
```@import "@blueprintjs/core/src/blueprint.scss";```
And set vars with new colors.
But when I build my application with webpack I have missed icons for checkbox and breadcumb.
In output styles I have:
`background-image: svg-icon("16px/small-tick.svg", (path: (fill: #ffffff)))`
But I should have:
`background-image: url(<data:svg....>)`
Looks like custom function `svg-icon` is not in compile process. I found this function in src but I don't know how to use it with sass-loader.

**Comment by giladgray** [comment] 2018-10-22 17:31
duplicate of #2986

**Closed by giladgray** 2018-10-22 17:31 UTC
