### ISSUE TITLE
Select Intent box for progress bar does not change after selection

### ISSUE THREAD

**Issue by abrooksv** [palantir/blueprint#165] opened 2016-11-15 03:28 UTC
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Windows 10, Firefox 49.0.2

#### Describe the issue:

1.  Go to http://blueprintjs.com/docs/#components.progress
2.  Select a different Intent, progress bar changes but the select box always says 'None'

#### Actual behavior:

Progress bar changes but not the select box

#### Expected behavior:

The progress bar should change as well as the selected value in the select box

**Comment by abrooksv** [comment] 2016-11-15 03:31
Intent select for spinner on  same page does the same thing

**Comment by giladgray** [comment] 2016-11-15 03:36
dear sir, allow me to blow your mind: try again _now_.

this is a duplicate of #154 which was resolved a few hours ago!

**Closed by giladgray** 2016-11-15 03:36 UTC
