### ISSUE TITLE
Menu does not give context to popover

### ISSUE THREAD

**Issue by rmendelovits** [palantir/blueprint#1299] opened 2017-06-29 15:26 UTC
### Bug report

- __Package version(s)__: 
- `"@blueprintjs/core": "^1.20.0",`
- `"@blueprintjs/datetime": "^1.17.0",`
- `"@blueprintjs/table": "^1.17.0"`
- `__Browser and OS versions__:
- Chrome Version 58.0.3029.110
- Windows 7 Professional

#### Steps to reproduce

1. Download this example: https://github.com/palantir/blueprint/blob/master/packages/table/examples/tableSortableExample.tsx
2. Change menu to renderMenu
3. run the program

#### Actual behavior

popover.js:168 [Blueprint] Disabling <Popover> with empty/whitespace content...
Popover.render	@	popover.js:168
(anonymous)	@	ReactCompositeComponent.js:795
measureLifeCyclePerf	@	ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext	@	ReactCompositeComponent.js:794
_renderValidatedComponent	@	ReactCompositeComponent.js:821
_updateRenderedComponent	@	ReactCompositeComponent.js:745
_performComponentUpdate	@	ReactCompositeComponent.js:723
updateComponent	@	ReactCompositeComponent.js:644
performUpdateIfNecessary	@	ReactCompositeComponent.js:560
performUpdateIfNecessary	@	ReactReconciler.js:156
runBatchedUpdates	@	ReactUpdates.js:150
perform	@	Transaction.js:143
perform	@	Transaction.js:143
perform	@	ReactUpdates.js:89
flushBatchedUpdates	@	ReactUpdates.js:172
closeAll	@	Transaction.js:209
perform	@	Transaction.js:156
batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
batchedUpdates	@	ReactUpdates.js:97
dispatchEvent	@	ReactEventListener.js:147

#### Expected behavior

Shows sorting menu

**Comment by giladgray** [comment] 2017-07-01 08:59
I think this is a duplicate of the issue described in #1121: React context is not inherited by context menus.

**Closed** 2017-07-07 19:32 UTC
Labels: Package: table, Type: question
