### ISSUE TITLE
doc-app build failed

### ISSUE THREAD

**Issue by crokobit** [palantir/blueprint#3782] opened 2019-10-17 10:24 UTC
#### Environment

- __Package version(s)__: @blueprintjs/select@3.11.1 
- __Browser and OS versions__: 

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1. git clone repo
2. run `yarn` in packages/docs-app/ folder

#### Actual behavior

Have errors

#### Expected behavior

Should have no errors.

#### Errors
```
 @blueprintjs/select@3.11.1 $ yarn
yarn install v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "js-yaml@3.13.1" is incompatible with requested version "js-yaml@~3.6.0"
[3/5] 🚚  Fetching packages...
warning better-handlebars@0.1.1: The engine "atom" appears to be invalid.
warning language-less@0.34.3: The engine "atom" appears to be invalid.
[4/5] 🔗  Linking dependencies...
warning " > stylelint-config-palantir@4.0.0" has unmet peer dependency "stylelint@^9.8.0".
warning "stylelint-config-palantir > stylelint-config-standard@18.3.0" has unmet peer dependency "stylelint@^8.3.0 || ^9.0.0 || ^10.0.0".
warning "stylelint-config-palantir > stylelint-order@2.2.1" has unmet peer dependency "stylelint@^9.10.1 || ^10.0.0".
warning " > stylelint-scss@3.9.2" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0 || ^10.0.0".
warning "stylelint-config-palantir > stylelint-config-standard > stylelint-config-recommended@2.2.0" has unmet peer dependency "stylelint@^8.3.0 || ^9.0.0 || ^10.0.0".
warning " > @blueprintjs/core@3.19.1" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/core@3.19.1" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/datetime@3.14.0" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/datetime@3.14.0" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/select@3.11.1" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/select@3.11.1" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/table@3.8.1" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/table@3.8.1" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/test-commons@0.10.0" has unmet peer dependency "react@>=15.3.0".
warning " > @blueprintjs/timezone@3.6.0" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/timezone@3.6.0" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/tslint-config@1.9.0" has unmet peer dependency "tslint@^5.12.1".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/core > sass-inline-svg@1.2.0" has unmet peer dependency "node-sass@^4.5.3".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/core > webpack-cli@3.3.6" has unmet peer dependency "webpack@4.x.x".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/docs-app > webpack-dev-server@3.7.2" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/karma-build-scripts > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/karma-build-scripts > karma-webpack@4.0.2" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.0" has incorrect peer dependency "react@^15.5.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.0" has unmet peer dependency "react-dom@^15.5.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.0" has unmet peer dependency "react-test-renderer@^15.5.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/test-commons > enzyme-adapter-react-16@1.14.0" has unmet peer dependency "react-dom@^16.0.0-0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/tslint-config > tslint-plugin-prettier@2.0.1" has unmet peer dependency "tslint@^5.0.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/tslint-config > tslint-react@4.0.0" has unmet peer dependency "tslint@^5.1.0".
warning "workspace-aggregator-1e5b344c-d411-4a51-aec9-1e2f477dec6b > @blueprintjs/docs-app > webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
[5/5] 🔨  Building fresh packages...
[-/8] ⠁ waiting...
[-/8] ⠁ waiting...
[8/8] ⠁ tree-sitter-typescript
[-/8] ⠂ waiting...
error /Users/crokobit/Office/blueprint/node_modules/tree-sitter-typescript: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/crokobit/Office/blueprint/node_modules/tree-sitter-typescript
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.10.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/crokobit/Office/blueprint/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/crokobit/Office/blueprint/node_modules/tree-sitter-typescript/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/crokobit/Office/blueprint/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/crokobit/.node-gyp/12.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/crokobit/.node-gyp/12.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/crokobit/Office/blueprint/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/crokobit/.node-gyp/12.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/crokobit/Office/blueprint/node_modules/tree-sitter-typescript',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/tree_sitter_tsx_binding/tsx/src/parser.o
  CC(target) Release/obj.target/tree_sitter_tsx_binding/tsx/src/scanner.o
  CXX(target) Release/obj.target/tree_sitter_tsx_binding/tsx/src/binding.o
../tsx/src/binding.cc:13:6: error: variable has incomplete type 'void'
void Init(Handle<Object> exports, Handle<Object> module) {
     ^
../tsx/src/binding.cc:13:11: error: use of undeclared identifier 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
          ^
../tsx/src/binding.cc:13:18: error: 'Object' does not refer to a value
void Init(Handle<Object> exports, Handle<Object> module) {
                 ^
/Users/crokobit/.node-gyp/12.10.0/include/node/v8.h:3369:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../tsx/src/binding.cc:13:26: error: use of undeclared identifier 'exports'
void Init(Handle<Object> exports, Handle<Object> module) {
                         ^
../tsx/src/binding.cc:13:35: error: use of undeclared identifier 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
                                  ^
../tsx/src/binding.cc:13:42: error: 'Object' does not refer to a value
void Init(Handle<Object> exports, Handle<Object> module) {
                                         ^
/Users/crokobit/.node-gyp/12.10.0/include/node/v8.h:3369:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../tsx/src/binding.cc:13:50: error: use of undeclared identifier 'module'
void Init(Handle<Object> exports, Handle<Object> module) {
                                                 ^
../tsx/src/binding.cc:13:57: error: expected ';' after top level declarator
void Init(Handle<Object> exports, Handle<Object> module) {
                                                        ^
                                                        ;
8 errors generated.
make: *** [Release/obj.target/tree_sitter_tsx_binding/tsx/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/crokobit/Office/blueprint/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/crokobit/.asdf/installs/nodejs/12.10.0/bin/node" "/Users/crokobit/Office/blueprint/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/crokobit/Office/blueprint/node_modules/tree-sitter-typescript
```

**Comment by crokobit** [comment] 2019-10-23 08:23
Need help 😢

**Comment by adidahiya** [comment] 2019-10-29 23:07
duplicate of #3799, which has a little more info

**Closed by adidahiya** 2019-10-29 23:07 UTC
