### ISSUE TITLE
Icon intent in ContextMenu does not changed

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#4187] opened 2020-06-23 17:04 UTC
Hi

I have a contextMenu

please checck this sandbox

https://codesandbox.io/s/blueprint-sandbox-jsijw?file=/src/index.tsx

Why icon intent doesn't changed? I 've tried with dark theme but same problem

**Comment by adidahiya** [comment] 2020-06-23 17:44
Duplicate of https://github.com/palantir/blueprint/issues/3593

**Closed by adidahiya** 2020-06-23 17:44 UTC
