### ISSUE TITLE
Pin to window popover example not working

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#800] opened 2017-03-07 18:01 UTC
### Bug report

- __Package version(s)__: 1.11.0
- __Browser and OS versions__: macOS Sierra, Chrome 56

#### Steps to reproduce

1. http://blueprintjs.com/docs/#components.popover
1. Click "Pin to window"

#### Actual behavior

![erre](https://cloud.githubusercontent.com/assets/199754/23670567/fbd88e12-031c-11e7-8cba-155dba779a32.gif)

#### Expected behavior

The popover is pinned to the window

**Comment by adidahiya** [comment] 2017-03-07 21:59
related, probably a duplicate of #100

**Comment by giladgray** [comment] 2017-03-14 19:12
definitely a duplicate of #100

**Closed by giladgray** 2017-03-14 19:12 UTC
Labels: Package: core, Type: bug
