### ISSUE TITLE
Cant scroll drawer when the content is overflow on documentation website

### ISSUE THREAD

**Issue by zizizheng** [palantir/blueprint#3564] opened 2019-05-23 02:19 UTC
#### Environment

- __Package version(s)__:  none
- __Browser and OS versions__: Chrome 74.0.3729.157

#### Steps to reproduce

1. go to [this page](https://blueprintjs.com/docs/#core/components/drawer) and click `IOverlayableProps` to invoke the drawer
1. It always happens when the content of drawer is overflow

#### Actual behavior

the content of the drawer is cut and cant be scrolled

#### Expected behavior

should be scrollable 

#### Possible solution

add css rule `overflow-y: scroll` to `div.bp3-drawer` element

**Comment by adidahiya** [comment] 2019-05-23 22:38
duplicate of #3512

**Closed by adidahiya** 2019-05-23 22:38 UTC
