### ISSUE TITLE
Toast Styling broken in 2.0.0-rc.3

### ISSUE THREAD

**Issue by k-simons** [palantir/blueprint#2234] opened 2018-03-14 16:18 UTC
### Bug report

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Steps to reproduce
- Create a toast on the docs site 
- This only happens when jumping from blueprint 2, rc2 ->  blueprint 2, rc3
#### Expected behavior

<img width="1025" alt="screen shot 2018-03-14 at 9 17 22 am" src="https://user-images.githubusercontent.com/16883861/37415396-92e89c8c-2768-11e8-8bbd-2e35c623034a.png">

**Comment by adidahiya** [comment] 2018-03-14 16:23
dupe of #2232

**Closed by adidahiya** 2018-03-14 16:23 UTC
