### ISSUE TITLE
Use React.PureComponent instead of @PureRender mixin

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#662] opened 2017-02-10 03:47 UTC
Let's use the the builtin `React.PureComponent`. This will allow us to remove our dependency on the `@PureRender` mixin.

**Comment by JKillian** [comment] 2017-02-10 04:50
Duplicate of https://github.com/palantir/blueprint/issues/144

**Closed by JKillian** 2017-02-10 04:50 UTC
Labels: Type: refactor
