### ISSUE TITLE
Menu items out of focus, fuzzy in a > 1920x1080 display.

### ISSUE THREAD

**Issue by johnunclesam** [palantir/blueprint#2391] opened 2018-04-16 12:10 UTC
### Bug report

- __Package version(s)__: 2.1.1
- __Browser and OS versions__: Chrome 65, Win 10

![image](https://user-images.githubusercontent.com/21275217/38808218-a282ba5c-417f-11e8-8923-2c5184ba5225.png)

Is this a problem for display > 1920x1080 pixel. Why?

**Blue line is OK** as you see...

If I open the "Settings" menu them are ok! Crazy fuzzy menu items!

See:

![image](https://user-images.githubusercontent.com/21275217/38808291-e8cc6896-417f-11e8-8c23-407e7619e32c.png)

**Comment by giladgray** [comment] 2018-04-16 16:34
duplicate of #394 (long discussion there, starting with the same screenshot)

this is a known issue with popovers on screens (generally) due to sub-pixel rendering. it's a browser thing, not a blueprint thing.

**Closed by giladgray** 2018-04-16 16:34 UTC

**Comment by johnunclesam** [comment] 2018-04-16 16:51
So there is no hope?

**Comment by giladgray** [comment] 2018-04-16 16:54
there is little hope. avoid half pixels if you can. follow the other discussion for tips.

**Comment by johnunclesam** [comment] 2018-04-18 09:46
What do you mean with "avoid half pixels", @giladgray?
