### ISSUE TITLE
"Hotkeys" component documentation showstopper

### ISSUE THREAD

**Issue by snackaholic** [palantir/blueprint#5073] opened 2021-12-14 13:52 UTC
#### Environment

- __Operating System__: 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"

- __Browser name and version__: Firefox 95.0

#### Steps to reproduce

Navigate to https://blueprintjs.com/docs/#core/components/html-table
Click on the hotkeys link

![grafik](https://user-images.githubusercontent.com/36051495/146010635-474a750b-dca6-477c-9738-ad7eb6e051fa.png)

#### Actual behavior

You  get a white page

![grafik](https://user-images.githubusercontent.com/36051495/146010548-7ea3efa4-df86-4151-95ee-3cd863da7860.png)

#### Expected behavior

You should see the documentation of the hotkeys component
https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/hotkeys/hotkeys.md

**Comment by adidahiya** [comment] 2021-12-14 20:02
Looks like that page doesn't work in Firefox at the moment because of our usage of WebAudio APIs. For now, you can work around this by using Chrome, but I will look into fixing this page so that it works in Firefox.

**Comment by PetrusAsikainen** [comment] 2023-11-01 13:20
Seems like a dupe of #6155 (fixed)

**Closed as completed** 2023-11-01 13:51 UTC
Labels: Type: bug, Domain: documentation, P3, Browser: Firefox, help wanted
