### ISSUE TITLE
NumericInput buttons height doesn't always match InputGroup height

### ISSUE THREAD

**Issue by ejose19** [palantir/blueprint#4278] opened 2020-08-11 23:01 UTC
#### Environment

- __Package version(s)__: Any version
- __Operating System__: Linux
- __Browser name and version__: Both Firefox and Chromium

#### Code Sandbox

[sandbox](https://codesandbox.io/s/recursing-christian-f2sji?file=/src/App.tsx)

#### Steps to reproduce

1. Create a NumericInput and notice the buttons height, it's off relative to inputgroup height by 1-2px, zooming in/out makes it change and sometimes they match, but this is not reliable

#### Actual behavior

Their height doesn't match (inputgroup is always fixed at 30px, buttons may range from 29px to 32px repending on zoom)

#### Expected behavior

Their height should always match

#### Notes

Applying overflow: hidden to the bp3-button-group div prevents it from exceeding the 30px, but on zooming it may be 29px.

**Comment by adidahiya** [comment] 2020-08-12 02:14
Duplicate of https://github.com/palantir/blueprint/issues/4044

**Closed as completed by adidahiya** 2020-08-12 02:14 UTC
Labels: Resolution: duplicate
