### ISSUE TITLE
Performance : Select2 is slow for 2000 items

### ISSUE THREAD

**Issue by peter-goodfill** [palantir/blueprint#5759] opened 2022-11-18 15:39 UTC
(actually for 800, but for demo purpose I chose 2000 so it is more visible)

#### Environment

- __Package version(s)__: `4.12.0`
- __Operating System__: `Ubuntu`
- __Browser name and version__: `Chrome 107.0.5304.87`

#### Code Sandbox
For was not working so I have created my own:

https://codesandbox.io/s/loving-ace-usf98j?file=/src/App.tsx

#### Steps to reproduce

1. Click on select box
2. There is a delay before dropdown shows up
3. Try to type into filter, event there is not filter function (predicate) its laggy

#### Actual behavior

It very slow to render dropdown

#### Expected behavior

Drop-down box opens rather quickly

#### Possible solution

I am not the expert but I believe there needs to be some kind of virtualized scroll. So only visible items are rendered.

**Comment by adidahiya** [comment] 2022-11-18 18:50
For very large lists you are recommended to virtualize rendering of the select component, and we provide the props (`itemListRenderer`, `itemRenderer`) that should allow you to do this with a third-party library. See related issues like https://github.com/palantir/blueprint/issues/2632 and https://github.com/palantir/blueprint/issues/4271.

Closing this as it's essentially a duplicate of #2632.

**Closed as completed by adidahiya** 2022-11-18 18:50 UTC
Labels: Resolution: duplicate
