### ISSUE TITLE
NumericInput clamping issue

### ISSUE THREAD

**Issue by SquareByte** [palantir/blueprint#6315] opened 2023-08-03 18:00 UTC
#### Environment

- __Package version(s)__: 5.0.0
- __Operating System__: Ubuntu Desktop Linux
- __Browser name and version__: Firefox 115, Chromium 115

#### Code Sandbox

https://codesandbox.io/s/elegant-easley-rgls9k?file=/src/App.tsx

#### Actual behavior

NumericInput shows "0" on initial render when passed props `stepSize={0.000001} minorStepSize={null} majorStepSize={null} value={0.001}` (the latter making it a controlled input).

Then on input focus the desired value suddenly pops up.

#### Expected behavior

Show the value `0.001`.

#### Possible solution

1. At least `NumericInput.roundAndClampValue` is broken, because `stepMaxPrecision`  is not passed to `toLocaleString`s option argument `maximumFractionDigits`.

```js
// in getDerivedStateFromProps():
const sanitizedValue = NumericInput.roundAndClampValue(/*value=*/"0.001", /*stepMaxPrecision=*/6, 0, 1, 0, "en")
// sanitizedValue is now "0"
```

2. Conceptually: as far as I understand it, `minor/major/stepSize` mix two distinct concerns: UI and data validation. For example: The user cannot control floats of arbitrary precision, and at the same time have a `minorStepSize` of say `0.01` for convenient input.

**Comment by PetrusAsikainen** [comment] 2023-08-07 17:38
I think this is a dupe of #4497?

**Comment by SquareByte** [comment] 2023-08-08 17:28
@PetrusAsikainen Yes, looks like it. Thank you.

I didn't recognized it because this issue focused on the button behavior. But the core issue is the same and more general, independent of the buttons. My sandbox has `buttonPosition="none"` set.

**Comment by TheRayTracer** [comment] 2023-08-08 22:52
This is a better dup: https://github.com/palantir/blueprint/issues/4045

**Closed as completed** 2023-08-25 14:16 UTC
Labels: Type: bug, Resolution: duplicate, Package: core
