### ISSUE TITLE
FR: Allow popovers to dynamically change size based on position

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#871] opened 2017-03-21 20:21 UTC
I have a popover that contains a Menu with many items. Ideally when I open it, it is as tall as it can be within the page, and scrolls if the page is too short

Current behavior: Popover jumps the page 
![image](https://cloud.githubusercontent.com/assets/24398123/24168934/3b79c2c6-0e39-11e7-9167-6738cd4ed95b.png)

Sorry the picture doesn't do a good job at explaining

**Comment by adidahiya** [comment] 2017-03-21 20:23
duplicate of #803

**Closed** 2017-03-21 20:26 UTC
