### ISSUE TITLE
Portal popover not positioned on mount (and jumpy on resize)

### ISSUE THREAD

**Issue by icd2k3** [palantir/blueprint#2352] opened 2018-04-03 19:58 UTC
### Bug report

- __Package version(s)__: 2.0.1
- __Browser and OS versions__: Chrome OSX

#### Actual behavior

Portal popover positioning is not set until a window resize event is triggered, and even then it is jumpy (see gif below). On open, the popover does not have any positioning set, then on window resize it continuously toggles between positioned and not positioned.

![portal](https://www.dropbox.com/s/gdgzp4psirhbd94/portal-popover.gif?raw=1)

#### Expected behavior

Portal popover positioning should be correct and not jump around when scrolling or resizing window.

#### Code
Pretty straightforward... 

```js
<Popover>
  <button>test</button>
  <div>
    tqwefqwef<br/>
    tqewfqwef<br/>
    tqwefqwef<br/>
  </div>
 </Popover>
```

Has anyone else run into this behavior?

**Comment by giladgray** [comment] 2018-04-03 20:08
@icd2k3 it looks like your container is simply too small for your popover, and so popper.js is getting too smart about positioning. try disabling the `preventOverflow` popper modifier: 
`modifiers={{ preventOverflow: { enabled: false}, hide: { enabled: false} }}`

**Comment by giladgray** [comment] 2018-04-03 20:32
huh, i have not encountered such a messed up state before! not sure what else to offer here.

**Comment by shadowmouse** [comment] 2018-04-03 20:35
I can also report encountering this issue since updating to 2.0.0 today. The Popover below is intended to appear directly under the "Admin Action Button"

Offending Code: 
`<Popover key={"nav-"+index} position={Position.BOTTOM} content={linkMenu} target={<button style={{ marginLeft: 5 }} className={"pt-button " + config.icon}> {config.label} </button>}/>`

Result:

![image](https://user-images.githubusercontent.com/6096692/38274379-e09e10cc-374b-11e8-94bf-c106223be005.png)

![image](https://user-images.githubusercontent.com/6096692/38274531-43b73cba-374c-11e8-9017-224d8e3b359f.png)

**Comment by icd2k3** [comment] 2018-04-03 20:46
@giladgray  I can confirm the above example works fine in `@blueprintjs/core@1.35.7` so this looks like a real bug in `2.0`... possibly related to the switch from `react-addons-css-transition-group` to `react-transition-group`? I know I ran into some positioning problems in my own app when making that switch.

**Comment by giladgray** [comment] 2018-04-03 20:48
oh no it's certainly due to switching the `Popover` positioning engine from Tether to Popper.js. you can try using `Popover2` in 1.x to see if you have the same results (i'm fairly certain you will).

**Comment by shadowmouse** [comment] 2018-04-03 21:00
I can also confirm some additional weirdness with the positioning when NOT using the Portal.

Example: 
`<Popover usePortal={false} position={Position.RIGHT_TOP} .../>`

Image: 
![image](https://user-images.githubusercontent.com/6096692/38275595-955271e0-374f-11e8-8110-3239f2c6833c.png)

**Comment by icd2k3** [comment] 2018-04-03 21:02
@giladgray you are absolutely right! Even in version `1.35.7` using `Portal2` produces the exact same result as the image above

**Comment by rage8885** [comment] 2018-04-03 21:10
I'm seeing a similar problem - it seems that the Popover is being positioned at top: 0 left: 0 - here is my code:

```
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import './global.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { Popover, Button, ButtonGroup, Position, Menu, MenuDivider, MenuItem } from '@blueprintjs/core';
import { FileMenu } from './components/menu1.js';

const container = document.getElementById('root');

ReactDOM.render((
  <div>
    <ButtonGroup vertical={true}>
      <Popover modifiers={{ preventOverflow: { enabled: false}, hide: { enabled: false} }}>
        <Button icon='refresh' intent='primary'></Button>
        <Menu>
          <MenuItem text="New" icon="document" />
          <MenuItem text="Open" icon="folder-shared" />
          <MenuItem text="Close" icon="add-to-folder" />
          <MenuDivider />
          <MenuItem text="Save" icon="floppy-disk" />
          <MenuItem text="Save as..." icon="floppy-disk" />
          <MenuDivider />
          <MenuItem text="Exit" icon="cross" />
        </Menu>
      </Popover>
      <Popover content={<FileMenu />}>
        <Button icon='zoom-in' intent='primary'></Button>
      </Popover>
    </ButtonGroup>
    <ButtonGroup vertical={true} className='buttonGroupRight'>
      <Button icon='refresh' intent='primary'></Button>
      <Button icon='zoom-in' intent='primary'></Button>
    </ButtonGroup>
  </div>
), container);
```

**Comment by shadowmouse** [comment] 2018-04-03 21:26
It looks like this may be an issue with the underlying react-popper element. Using react-popper in the following setup has a similar issue.

Code: 

```
import { Manager, Target, Popper, Arrow } from 'react-popper'

<Manager>
  <Target>
    <button className="pt-button" type="submit"> Select Download Fields </button>
  </Target>
  <Popper placement={"right"}>
    <div style={{padding: 10, backgroundColor: "white", border: "black 1px solid"}}>
      Popper Test
    </div>
  </Popper>
</Manager>
```
> </Manager>

Result: 
![image](https://user-images.githubusercontent.com/6096692/38276662-f37bc836-3752-11e8-891f-bff0986156ec.png)

**Comment by tyscorp** [comment] 2018-04-03 21:46
This is caused by https://github.com/FezVrasta/popper.js/pull/596 which was released in popper.js@1.14.2.

**Comment by icd2k3** [comment] 2018-04-03 21:52
Similarly to @shadowmouse I tried using only `react-popper` with a portal component wrapper (which is not officially supported by `react-popper`, by the way) and I can replicate this same positioning issue.

ex:
```js
import { Manager, Target, Popper, Arrow } from 'react-popper';

<Manager>
  <Target style={{ width: 120, height: 120, background: '#b4da55' }}>
    Target Box
  </Target>
  <Portal>
    <Popper placement="left">
      <div>Popover Example</div>
    </Popper>
  </Portal>
</Manager>
```

**Comment by icd2k3** [comment] 2018-04-03 22:02
@tyscorp is correct. Using that example above with popper.js `v1.14.1` fixes the issue

**Comment by giladgray** [comment] 2018-04-03 22:27
@tyscorp are you saying that there's a bug in the latest popper.js release? is there an issue on that repo to track fixing it?

**Comment by shadowmouse** [comment] 2018-04-04 15:42
Popper.js has been updated to 1.14.3 and corrects the issue. An npm update fixed this for me.

**Comment by shadowmouse** [comment] 2018-04-04 16:45
Same Behavior confirmed in react-popper element. I'll just take the bug report over to either react-popper or popper.js directly.

**Comment by giladgray** [comment] 2018-04-04 18:36
@shadowmouse the popover position is expected given the DOM state your screenshot shows. adjusting CSS display is the correct approach.

seems like this was an issue in popper.js and has been resolved in the latest release.

**Comment by giladgray** [comment] 2018-04-12 21:34
resolved by popper.js @ 1.14.3

**Closed by giladgray** 2018-04-12 21:34 UTC
Labels: Package: core, Resolution: external, Type: question
