### ISSUE TITLE
EditableText's `onCancel` Prop Doesn't Fire On `<esc>`

### ISSUE THREAD

**Issue by leonyjiang** [palantir/blueprint#4779] opened 2021-06-24 02:54 UTC
#### Environment

- __Package version(s)__:
  - @blueprintjs/core: 3.46.0
  - react: 17.0.2
  - react-dom: 17.0.2
- __Operating System__: macOS Big Sur 11.4
- __Browser name and version__: Google Chrome, Version 91.0.4472.114 (latest)

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-editabletext-oncancel-bug-pkjwz

#### Steps to reproduce

1. Create a new React app (`npx create-react-app my-app --template typescript`)
2. Install blueprintjs (`yarn add @blueprintjs/core react react-dom`, add CSS imports)
3. Use the `<EditableText />` component with `onCancel` prop and try `<esc>`ing

#### Actual behavior
`onConfirm` is triggered.

#### Expected behavior
`onCancel` triggered.

#### Possible solution
Haven't looked at the source code yet but was wondering if this is a known issue or if there's an easy fix.

**Comment by adidahiya** [comment] 2021-06-24 15:53
Thanks for the clear repro and sandbox. This looks like the same issue as this very old issue: https://github.com/palantir/blueprint/issues/975. Looks like it was never fixed properly, for some reason. The test suite is buggy / not representative of real behavior.

**Comment by leonyjiang** [comment] 2021-07-07 07:55
Hi Adi, I want to take a look at this in-depth. Running `yarn` after cloning the repo, however, fails due to my `node` having major version 16 (requirement is `">=12 <14"`). It also seems that [blueprint v4](https://blueprintjs.com/docs/versions/4/) is in pre-release. That being said, what does the roadmap for v4 look like, i.e. estimated release date? Is there a way for me to contribute directly to v4 via GitHub?

**Comment by adidahiya** [comment] 2021-07-07 18:55
@leonyjiang v4 will be released in the next couple months. For now please contribute to 3.x, and your changes will get merged into the v4 branch. Yes we have a Node engine constraint. Please use a Node version manager like `nvm` to get a compatible version running on your machine.

**Comment by synapse** [comment] 2022-01-04 14:11
@adidahiya is there a way to prevent the event to propagate when hitting the Esc key?

**Comment by michael-yx-wu** [comment] 2022-06-28 22:11
@adidahiya this can probably be closed. The error no longer reproduces in the sandbox in Safari or Chrome

**Closed as completed** 2022-07-07 15:43 UTC
Labels: Type: bug, Resolution: fixed, P2, help wanted
