### ISSUE TITLE
Date Range hover shows a wrong date on the selected date

### ISSUE THREAD

**Issue by rveciana** [palantir/blueprint#4875] opened 2021-08-24 08:38 UTC
#### Environment

- __Package version(s)__: develop branch (and all other branches I tested)
- __Operating System__: Windows
- __Browser name and version__: Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)

#### Steps to reproduce

- Select an initial date
- Hover any other date on the calendar -> The input field shows it
- Hover the already selected date -> The shown date is 1/1/[year]

![dateRangeBlueprint](https://user-images.githubusercontent.com/2832885/130583903-5d6527e8-7301-43ac-8404-ac8ad44a2a77.gif)

#### Actual behavior

When the calendar is open on a Date Range component, hovering the calendar days change the input field with the date selected on the calendar. When hovering the already selected day, the value in the input field is 1/1/[selected year], no the actual date.

#### Expected behavior

The date shown in the input field should be the hovered date

**Comment by adidahiya** [comment] 2021-08-24 14:43
Confirmed, I can repro this in the [DateRangeInput docs example](https://blueprintjs.com/docs/#datetime/daterangeinput)

**Comment by evansjohnson** [comment] 2024-06-17 12:16
I think the intent here is to show that the current date will be unselected upon click. In this case the default state shows the format of the date, Jan 1st 20 years ago - and this is the state shown again on hover.

`DateRangeInput`:
<img width="658" alt="Screenshot 2024-06-17 at 8 12 33 AM" src="https://github.com/palantir/blueprint/assets/14102129/a8121f96-c401-44ed-96b6-ddc676f97758">

---

`DateRangeInput3` has arguably better behavior, where instead of this "placeholder" start date, the text "Start date" is shown, in both the default case, and when hovering the currently selected start date.

`DateRangeInput3`:
<img width="665" alt="Screenshot 2024-06-17 at 8 11 09 AM" src="https://github.com/palantir/blueprint/assets/14102129/32a6eadc-8491-4b91-8aa2-130576bfc49a">
<img width="727" alt="Screenshot 2024-06-17 at 8 11 05 AM" src="https://github.com/palantir/blueprint/assets/14102129/272da7df-cf12-4cb4-aa84-e6aa339f1abf">

---

Closing since this behavior only appears on the deprecated `DateRangeInput`, is arguably expected behavior, and there's been no additional interest on this ticket.

**Closed as not planned by evansjohnson** 2024-06-17 12:16 UTC
Labels: Type: bug, P2, help wanted, Package: datetime
