### ISSUE TITLE
copy "Invalid date" or "Out of range" into date input component will crash the component

### ISSUE THREAD

**Issue by chaomao** [palantir/blueprint#4433] opened 2020-11-26 07:30 UTC
#### Environment

- __Package version(s)__: 3.18.2
- __Operating System__: mac os 10.15.7
- __Browser name and version__: chrome 

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-7hc56?file=/src/index.tsx

#### Steps to reproduce

1. copy "Invalid date"
2. paste into date input component
3. component will crash

#### Actual behavior

Error: Cannot read property 'valueOf' of null found

#### Expected behavior

empty value or current date into date input component

#### Possible solution

here is the issue, https://github.com/palantir/blueprint/blob/241b20d5b45a62ef90c91d795f78d429adbda47f/packages/datetime/src/dateInput.tsx#L366-L380

```
// date will be null if valueString is "Invalid date" or "Out of range"
const date = this.parseDate(valueString);
...
// we need check date is not null before invoke valueOf method
if (isNaN(date.valueOf())) {
```

**Comment by devjuliet** [comment] 2020-12-08 19:24
@adidahiya @chaomao Is this up for grabs?

**Comment by adidahiya** [comment] 2020-12-08 20:29
The original code sandbox does not show the problem; it doesn't use `DateInput`. Can you post a new sandbox using the latest versions of core and datetime packages?

**Comment by chaomao** [comment] 2020-12-14 02:29
@adidahiya
sorry for the confusion, I already update the sandbox, which can reproduce the issue, please look it again

**Comment by adidahiya** [comment] 2020-12-14 15:53
Duplicate of #4251 and #4376

**Closed as completed by adidahiya** 2020-12-14 15:53 UTC
Labels: Resolution: duplicate, Package: datetime
