### ISSUE TITLE
table overflowing ellipses doesn't get recomputed on column resize

### ISSUE THREAD

**Issue by hellochar** [palantir/blueprint#664] opened 2017-02-10 15:39 UTC
### Bug report

- __Package version(s)__: blueprintjs/table@1.4.1
- __Browser and OS versions__: Chrome latest; OSX 10.11.16

#### Steps to reproduce

1. Create an overflowing column such that ellipses are shown
1. expand the column

#### Actual behavior

Ellipses doesn't go away on any resize
![image](https://cloud.githubusercontent.com/assets/1079495/22832703/68fa76c6-efaf-11e6-989e-937fe5e9a782.png)

#### Expected behavior

Ellipses disappears when you expand, and appears when you shrink

**Comment by llorca** [comment] 2017-02-10 18:21
Dupe of #604, follow along #634

**Closed by llorca** 2017-02-10 18:21 UTC
