### ISSUE TITLE
"File URL Path must be absolute" warning when building with Webpack

### ISSUE THREAD

**Issue by stur86** [palantir/blueprint#5276] opened 2022-04-28 10:21 UTC
#### Environment

- __Package version(s)__: Blueprint v 4.2.1, Webpack v 5.72.0
- __Operating System__: Windows 11
- __Browser name and version__: Not relevant

#### Steps to reproduce

1. Start a project configured to use Webpack for building, for example with `create-react-app`
2. install and import `@blueprintjs` in one of the files
3. run a build job or use `npm start` to run the development server

#### Actual behavior

The build produces a lot of warnings of this sort:

```
WARNING in ./node_modules/@blueprintjs/core/lib/css/blueprint.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/@blueprintjs/core/lib/css/blueprint.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
File URL path must be absolute
```

(I get 72 of them between Core, Select and Icons)

#### Expected behavior

No warnings. Currently just an annoyance but I would like to know if they can be symptom of a potential issue.

**Comment by ysalo** [comment] 2022-05-16 22:27
Facing the same issue with Blueprint v 4.3.0

**Comment by adidahiya** [comment] 2022-05-17 14:23
Duplicate of #5274... we have some issues with the file paths generated in CSS source maps in recent releases

**Closed as completed by adidahiya** 2022-05-17 14:23 UTC
Labels: Resolution: duplicate
