### ISSUE TITLE
Context menu scrolls page when triggered

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#273] opened 2016-11-30 00:42 UTC
### Bug Report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Firefox 48

#### Describe the issue:

![contextm](https://cloud.githubusercontent.com/assets/199754/20735115/c4fba97c-b652-11e6-9a54-0c53bfec2ae7.gif)

#### Actual behavior:

Context menu opens and the page scrolls, causing loss of context for users

#### Expected behavior:

Context menu appears without scrolling the page

**Comment by giladgray** [comment] 2016-11-30 01:13
same issue as #183

**Comment by adidahiya** [comment] 2016-11-30 15:13
more accurately, this is a duplicate of #231

**Closed by adidahiya** 2016-11-30 15:13 UTC
Labels: P2, Type: bug
