### ISSUE TITLE
Blueprint Table is slow with large tables in Firefox

### ISSUE THREAD

**Issue by greglo** [palantir/blueprint#732] opened 2017-02-24 22:40 UTC
macOS 10.11.6 on a Retina, 15-inch, mid 2014 macbook pro. Browser is Firefox 51.0.1 64-bit.

Perf is pretty bad when scrolling/interacting with the UI. I'm experiencing this on Firefox, and to a lesser extent on Chrome.

**Comment by llorca** [comment] 2017-02-24 22:48
Dupe of #390

**Closed by llorca** 2017-02-24 22:48 UTC
