### ISSUE TITLE
NumericInput selects text when used in a Dialog

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#3195] opened 2018-11-30 18:49 UTC
#### Environment

- __Package version(s)__: 3.9.0
- __Browser and OS versions__: chrome 70.0.3538.110, mac os 10.14.1

#### Steps to reproduce

```
class App extends Component {
  render() {
    return (
      <div className="App">
        <Dialog isOpen>
          <NumericInput />I am some text
        </Dialog>
      </div>
    );
  }
}
```

#### Actual behavior

![blueprint-numeric](https://user-images.githubusercontent.com/10415101/49308580-87295880-f48d-11e8-859b-1a66ded30767.gif)

https://github.com/tgreen7/blueprint-numeric-select-text

#### Expected behavior

To not select text

**Comment by giladgray** [comment] 2018-12-01 01:05
duplicate of #3004

**Closed by giladgray** 2018-12-01 01:05 UTC
