### ISSUE TITLE
Select: How to make popover same width as button?

### ISSUE THREAD

**Issue by danaugrs** [palantir/blueprint#4722] opened 2021-05-15 23:14 UTC
See below how the popover is not as wide as the button that shows it:

![Screenshot from 2021-05-15 19-58-37](https://user-images.githubusercontent.com/5261448/118380462-3b64be00-b5b8-11eb-82c8-72658dd87116.png)

It seems impossible to make the popover the same width as a (full-width) button with CSS alone.
Any ideas on how to solve this?

This seems like a pretty common scenario - it would be nice if there was a flag we could set on Select/MultiSelect/Suggest that would take care of this.

**Comment by adidahiya** [comment] 2021-05-18 16:17
duplicate of #2956

**Closed as completed by adidahiya** 2021-05-18 16:17 UTC
Labels: Resolution: duplicate
