### ISSUE TITLE
Feature Request: Support spanning multiple columns in a cell.

### ISSUE THREAD

**Issue by pselden** [palantir/blueprint#1734] opened 2017-10-18 21:00 UTC
I would like to be able to have a cell span multiple columns (in my particular use case it would be one cell spanning the entire row).

Is this sort of thing possible right now at all? It seems like I could sort of fake it if I set width to 100% and then did a z-index to cover the other rows in DevTools. If not, could you give some pointers about where I might look to implement such a feature here?

**Comment by giladgray** [comment] 2017-10-18 21:04
duplicate of #1691.

this is both not currently possible and outrageously expensive to implement. a real double header 😞

**Comment by cmslewis** [comment] 2017-11-03 17:53
Closing as dupe of #1691

**Closed** 2017-11-03 17:52 UTC
Labels: Package: table, Type: question
