### ISSUE TITLE
Popover2 subpixel arrow placement

### ISSUE THREAD

**Issue by Protectator** [palantir/blueprint#4525] opened 2021-02-14 17:05 UTC
#### Environment

- __Package version(s)__: 3.38.0
- __Operating System__: Windows 10
- __Browser name and version__: Version 88.0.4324.150 (64 bits)

#### Code Sandbox

This happens right on the official example's page for Popover2 (https://blueprintjs.com/docs/#popover2-package/popover2) :

#### Steps to reproduce

1. Use a display with a scaling higher than x1 (for example x1.5)
2. Open the Popover2 example page
3. Disable `usePortal`
4. Use `position` `right`
5. Click on the central example Button to display the Popover

#### Actual behavior

Scaling x1 ( OK ) : 
![image](https://user-images.githubusercontent.com/1529017/107883279-560e9480-6eee-11eb-9a0d-c8211db94dbd.png)

Scaling x1.5 ( WRONG ) :
![image](https://user-images.githubusercontent.com/1529017/107883310-85250600-6eee-11eb-9e1d-55f7b9d31816.png)

#### Expected behavior

I'd expect not to see any black line between the arrow and the Popover content in x1.5 scaling.

**Comment by adidahiya** [comment] 2021-02-15 19:07
This is a longstanding issue with popover layout when zoomed in. Open to ideas for fixing it... I'm all ears... duplicate of #1059, so let's keep discussion there.

**Closed as completed by adidahiya** 2021-02-15 19:07 UTC
Labels: Resolution: duplicate
