### ISSUE TITLE
Allow using arrow keys to navigate through menus

### ISSUE THREAD

**Issue by Nifdee** [palantir/blueprint#4910] opened 2021-09-15 14:49 UTC
#### Environment

- __Package version(s)__: core 3.49.1
- __Browser and OS versions__: 

#### Feature request

Menus are often used as dropdowns, where up and down arrows should be usable for navigating between menu items, and space should be usable to expand submenus.

**Comment by adidahiya** [comment] 2021-09-15 16:37
duplicate of https://github.com/palantir/blueprint/issues/3079

**Closed as completed by adidahiya** 2021-09-15 16:37 UTC
Labels: Resolution: duplicate
