### ISSUE TITLE
Menu should have a dark scrollbar in dark mode

### ISSUE THREAD

**Issue by mitchellirvin** [palantir/blueprint#4565] opened 2021-03-08 17:19 UTC
#### Environment

- __Package version(s)__: `"@blueprintjs/core": "^3.39.0"`
- __Browser and OS versions__: Chrome: Version 89.0.4389.72 (Official Build) (x86_64), macOS Catalina: version 10.15.7

#### Feature request
When a bp3-menu is in dark mode, it should have a dark styled scrollbar. 

#### Examples
[codesandbox](https://codesandbox.io/s/blueprint-sandbox-forked-zh39q)

**current state**
![image](https://user-images.githubusercontent.com/16233245/110356638-766ed200-8008-11eb-8b74-864773063da5.png)

**It seems like the dark scrollbar styles ought to be applied wherever we're setting the following style:**
![image](https://user-images.githubusercontent.com/16233245/110354910-ab7a2500-8006-11eb-8eb3-c45336efa049.png)

Here's a suggested style (can be viewed in the codesandbox)
![image](https://user-images.githubusercontent.com/16233245/110356716-88e90b80-8008-11eb-895c-f0c055eb2b7e.png)

**Comment by mitchellirvin** [comment] 2021-03-08 18:17
> #### Environment
> * **Package version(s)**: `"@blueprintjs/core": "^3.39.0"`
> * **Browser and OS versions**: Chrome: Version 89.0.4389.72 (Official Build) (x86_64), macOS Catalina: version 10.15.7
> 
> #### Feature request
> When a bp3-menu is in dark mode, it should have a dark styled scrollbar.
> 
> #### Examples
> [codesandbox](https://codesandbox.io/s/blueprint-sandbox-forked-zh39q)
> 
> **current state**
> ![image](https://user-images.githubusercontent.com/16233245/110356638-766ed200-8008-11eb-8b74-864773063da5.png)
> 
> **It seems like the dark scrollbar styles ought to be applied wherever we're setting the following style:**
> ![image](https://user-images.githubusercontent.com/16233245/110354910-ab7a2500-8006-11eb-8eb3-c45336efa049.png)
> 
> Here's a suggested style (can be viewed in the codesandbox)
> ![image](https://user-images.githubusercontent.com/16233245/110356716-88e90b80-8008-11eb-895c-f0c055eb2b7e.png)

**Comment by adidahiya** [comment] 2021-03-08 21:24
Duplicate of https://github.com/palantir/blueprint/issues/956

**Closed as completed by adidahiya** 2021-03-08 21:24 UTC
Labels: Resolution: duplicate
