### ISSUE TITLE
Multiple highlighted menu items in the navigator search bar on documentation page

### ISSUE THREAD

**Issue by pavelkang** [palantir/blueprint#395] opened 2016-12-30 00:39 UTC
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: Chrome 55.0.2883.95 (64-bit) macOS Sierra

#### Steps to reproduce

1. type a query in the navigator search bar on blueprint documentation page
2. Hover cursor over an item A, A is highlighted
3. press down/up arrow key. 

#### Actual behavior

Two items are highlighted

#### Expected behavior

I believe we want to remove the highlight effect from the item under the cursor

**Comment by giladgray** [comment] 2016-12-30 19:37
duplicate of #335

**Comment by JKillian** [comment] 2017-01-02 02:35
Closing as a duplicate

**Closed by JKillian** 2017-01-02 02:35 UTC
