### ISSUE TITLE
[Table] Maximum number of rows in a table is 200? 

### ISSUE THREAD

**Issue by jasonbarry** [palantir/blueprint#1400] opened 2017-08-01 07:04 UTC
https://github.com/palantir/blueprint/blob/10b1f58bcf581297ee4f2ccab3bdd11b5b7804e2/packages/table/src/common/grid.ts#L35

It seems like tables are hardcoded to be limited to 200 rows? Why is this the case? Are there any ways to circumvent this limitation?

Seems that the presence of `DEFAULT_MAX_ROWS` should be noted in the documentation.

### Bug report

- __Package version(s)__: blueprintjs/table 1.18.0
- __Browser and OS versions__: Safari 10.1.1 

#### Steps to reproduce

1. Create an array with greater than 200 items
2. Display it in a table

#### Actual behavior

The table gets truncated after the 200th item.

#### Expected behavior

All items of the array are printed to the table.

**Comment by llorca** [comment] 2017-08-01 17:16
It sure isn't limited to 200. Can you share how you're constructing your table?

**Comment by jasonbarry** [comment] 2017-08-01 17:53
I have a global array called `DATA` containing 220 objects like 

```JS
{
    address: "test@example.com", 
    name: "Testing", 
    subscribed: true, 
    vars: {
        created_at: 1501600580, 
        via: "Google"
    }
}
```

and then my component looks like 

```JS
renderColumnHeader = (columnIndex: number) => {
    let value = '';
    switch (columnIndex) {
        case 0: value = 'Name'; break;
        case 1: value = 'Email'; break;
        case 2: value = 'Sign-up Date'; break;
        case 3: value = 'Via'; break;
        default: value = ''; break;
    }
    return (
        <ColumnHeaderCell name={value} />
    );
};

getCellData = (rowIndex: number, columnIndex: number) => {
    const row = window.DATA[rowIndex];

    let value = '';
    if (columnIndex === 0) {
        value = row.name;
    } else if (columnIndex === 1) {
        value = row.address;
    } else if (columnIndex === 2) {
        value = '';
        if (row.vars.hasOwnProperty('created_at')) {
            const date = new Date(row.vars.created_at * 1000);
            value = date.toLocaleString();
        }
    } else if (columnIndex === 3) {
        value = '';
        if (row.vars.hasOwnProperty('via')) {
            value = row.vars.via;
        }
    }
    return value;
}

renderCell = (rowIndex: number, columnIndex: number) => {
    const value = this.getCellData(rowIndex, columnIndex);
    return (
        <Cell key={`cell-${rowIndex}-${columnIndex}`}>{value}</Cell>
    );
};

renderBodyContextMenu = (context: IMenuContext) => {
    return (
        <Menu>
            <CopyCellsMenuItem
                context={context}
                getCellData={this.getCellData}
                text="Copy"
            />
        </Menu>
    );
}

render() {
    return (
        <Table 
            numRows={window.DATA.length} 
            defaultColumnWidth={270}
            renderBodyContextMenu={this.renderBodyContextMenu}
            selectionModes={SelectionModes.COLUMNS_AND_CELLS}
            getCellClipboardData={this.getCellData}
        >
            <Column
                renderCell={this.renderCell}
                renderColumnHeader={this.renderColumnHeader}
            />
            <Column
                renderCell={this.renderCell}
                renderColumnHeader={this.renderColumnHeader}
            />
            <Column
                renderCell={this.renderCell}
                renderColumnHeader={this.renderColumnHeader}
            />
            <Column
                renderCell={this.renderCell}
                renderColumnHeader={this.renderColumnHeader}
            />
        </Table>
    );
}
```

Only 200 rows get printed.

**Comment by cmslewis** [comment] 2017-08-01 19:37
Huh, I'd never encountered this before since taking over the `Table` codebase, but it looks like only 200 rows will be shown _in the same scroll view_ (though you can of course scroll to reveal the rest). This is due to the table's assumption that it will be shown as a scrollable pane.

@jasonbarry How tall is your table container and how tall are your rows?

**Comment by jasonbarry** [comment] 2017-08-01 20:01
@cmslewis ah, that's probably it! My table container is 10000px because I wanted the window to be the main scroll view.

**Comment by cmslewis** [comment] 2017-08-01 20:06
Is it workable for you to have the table be your scrollable region for now (and style it to absolute-fill its parent container)?

**Comment by jasonbarry** [comment] 2017-08-01 20:40
@cmslewis Yes — although it's a little strange having two scrollbars now, since the table is the only content that's displayed on the page.

**Comment by giladgray** [comment] 2017-08-01 21:41
@jasonbarry you should be able to have only one scrollbar with a little CSS `overflow` wizardry.

**Comment by adidahiya** [comment] 2017-08-02 04:48
@jasonbarry I'm inclined to close this issue as "by design". Blueprint's table component is a "fixed" table kind of like [fixed-data-table](https://github.com/facebook/fixed-data-table); it doesn't grow or shrink based on its contents. You can use CSS to make the table fit its container element, but that's up to you. If you have a proposal for an alternative layout mechanism, we'd be willing to take a look (but it might be out of scope -- no guarantees that it'll be implemented or supported by us).

**Closed by adidahiya** 2017-08-02 04:48 UTC
Labels: Package: table, Status: in discussion

**Comment by tsheaff** [comment] 2018-01-11 19:26
My table just stretches down to the bottom of the page by default.  I see this css on the table

```css
.bp-table-container {
    transform: translateZ(0);
    display: flex;
    flex-direction: column;
    background-color: #f5f8fa;
    max-width: 100%;
    height: 100%;
    min-height: 60px;
    max-height: 100%;
    overflow: hidden;
}
```

Are you saying I need to limit the height of the page? The default overflow is `hidden` not `scroll`

**Comment by tsheaff** [comment] 2018-01-11 19:30
For posterity: you have to wrap it in a fixed-height container:

```
<div style={{height: "500px"}}>
    <Table .../>
</div>
```

I think this should be more explicitly documented on the docs.

**Comment by TonyaQi** [comment] 2019-04-02 06:04
> For posterity: you have to wrap it in a fixed-height container:
> 
> ```
> <div style={{height: "500px"}}>
>     <Table .../>
> </div>
> ```
> I think this should be more explicitly documented on the docs.

but when we set max-height .  it can't work good
