### ISSUE TITLE
Horizontal layout option for Collapse component

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#1045] opened 2017-04-27 17:16 UTC
Right now, `<Collapse>` children can only expand vertically. There are a number of use cases I've found for horizontal expansion. Often these are side panels or helpers for my application.

**Comment by PhilWelsh** [comment] 2020-05-02 21:23
i know this was an earlier post, but 3321 has more responses, so...
Duplicate of #3321

**Closed** 2020-05-02 23:23 UTC
Labels: Package: core, Resolution: duplicate, Type: feature request
