### ISSUE TITLE
EditableText's updateInputDImensions can sometimes lead to a React prevented infinite render

### ISSUE THREAD

**Issue by cyu06** [palantir/blueprint#3736] opened 2019-09-10 21:53 UTC
#### Environment

- __Package version(s)__: core 3.15.0
- __Browser and OS versions__: Mac Chrome 76/77

#### Steps to reproduce

1. EditableText with a minWidth of 0 in a parent with plentiful width to grow
2. Type in any of the following letters: [“a”, “e”, “k”, “l”, “m”, ”o”]

#### Actual behavior

React will crash to prevent infinite loop: https://reactjs.org/docs/error-decoder.html/?invariant=185

#### Expected behavior

All characters can be typed

#### Possible solution

We're seeing scrollWidth on the measured span (https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/editable-text/editableText.tsx#L354) oscillating between renders for the characters above. The input width keeps seesawing between a larger amount and the specified minWidth for single character presses. This leads to the infinite loop where the remeasuring then continues, setting state to a newer larger value, then resetting back to the smaller. The mis-measured `scrollWidth` could possibly also be a browser bug introduced in a more recent version of Chrome, possibly why this infinite loop has not been encountered in the past as easily.

**Comment by marvinsum** [comment] 2019-09-13 18:51
@cyu06 @ecwyne are you using the `min-width` prop? I've found the problem goes away if you don't declare a `min-width`.

**Comment by cyu06** [comment] 2019-09-13 20:30
Yes we were using a minWidth of 0. We could not unset this prop completely because the default width then takes more space than desired, so had to just keep testing with this value slightly increased until the oscillating measured scrollWidth disappeared. I think at minWidth approximately 20, you'd still get crashes inputs like `ggg`, on the third keystroke when the EditableText expands. Nonetheless, we set it finally to 25, and it reduces the likelihood of the crashing, though it takes a little more space in width than design desired.

**Comment by adidahiya** [comment] 2020-09-03 13:09
I believe this is a duplicate of https://github.com/palantir/blueprint/issues/4267, fixed by https://github.com/palantir/blueprint/pull/4268

**Closed by adidahiya** 2020-09-03 13:09 UTC
Labels: P2, Package: core, Type: bug, help wanted
