### ISSUE TITLE
Documentation Page breaks when changing locale of Numeric Input to Default

### ISSUE THREAD

**Issue by G-MAKROGLOU** [palantir/blueprint#5062] opened 2021-12-07 19:31 UTC
When changing the locale of the numeric input example in the documentation page, it throws a "Incorrect locale information provided at Number.toLocaleString" exception. To reproduce, just change the locale to another value and then change it back to default.

**Comment by adidahiya** [comment] 2022-01-05 17:19
duplicate of #4424

**Closed as completed by adidahiya** 2022-01-05 17:19 UTC
Labels: Resolution: duplicate
