### ISSUE TITLE
[DateInput] Add support for className prop

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#878] opened 2017-03-22 17:33 UTC
### Bug report

- __Package version(s)__: DateTime 1.9.1

#### Steps to reproduce

1. Set `className` on date input class.

#### Actual behavior

Class name does not show up on the input or the popover element.

#### Expected behavior

`className` should show up on the input or the popover target element (should probably be able to class names to both?).

**Comment by giladgray** [comment] 2017-03-22 18:23
seems like `<DateInput className>` gets sent to the `DatePicker`: https://github.com/palantir/blueprint/blob/master/packages/datetime/src/dateInput.tsx#L159-L160

**Comment by leebyp** [comment] 2017-03-23 10:36
Will be fixed as part of 2.x as per the discussion in #387

**Comment by adidahiya** [comment] 2017-03-23 15:21
dupe of #387

**Closed by adidahiya** 2017-03-23 15:21 UTC
Labels: Package: datetime, Type: bug
