### ISSUE TITLE
Automatically scroll to visible rows when `numRows` is reduced or expanded

### ISSUE THREAD

**Issue by themadcreator** [palantir/blueprint#533] opened 2017-01-23 19:59 UTC
### Bug report

**v1.6.0**

If you are scrolled to the bottom of a large table, then the `numRows` prop is reduced, the scroll position is **not** updated so it looks like there are no rows in the table.

Users can scroll up themselves to see the rows, but a better solution would be to adjust the scroll position automatically when the number of rows is reduced. Care should be taken to deal with tables that don't have enough rows to fill a full screen (or available the table area).

#### Steps to reproduce

1. Create table with many `10000` rows
1. Scroll to bottom
1. Update `numRows` prop to `100` or  `5`

#### Actual behavior

You are greeted with a large empty gray space

#### Expected behavior

Scrolls you to some visible rows

**Comment by llorca** [comment] 2017-01-23 20:20
Dupe of #532... I'll close it out.

Note that this should work both when **reducing** and **expanding** the number of rows.

**Comment by cmslewis** [comment] 2017-05-15 22:34
@themadcreator @llorca I can't repro this. Here's an example of toggling `nRows` between `1000` and `500`.

![2017-05-15 15 33 18](https://cloud.githubusercontent.com/assets/443450/26082287/f9a99670-3983-11e7-8b2b-01f3fcc8fae3.gif)

**Comment by tgreenwatts** [comment] 2017-05-17 18:00
OK I think we can close this then!

**Comment by cmslewis** [comment] 2017-05-25 09:12
I finally was able to repro! This issue manifests when you change the number of rows _while ghost cells are enabled_. We should submit a fix.

**Closed** 2017-06-12 18:12 UTC
Labels: Package: table, Status: needs more info, Type: enhancement
