### ISSUE TITLE
Drawer align left

### ISSUE THREAD

**Issue by haThaiHoang** [palantir/blueprint#3378] opened 2019-02-26 10:18 UTC
Thank for great library. Please help me with this
How can i user Drawer with transition from the left to the right

**Comment by Ackos95** [comment] 2019-02-26 22:45
:+1: for qustion, I'm interested as well. Same issue already exists #3360

**Comment by adidahiya** [comment] 2019-02-26 22:46
duplicate of #3360

**Closed by adidahiya** 2019-02-26 22:46 UTC
