### ISSUE TITLE
[Overlay] Inline overlays with backdrops do not close on outside click

### ISSUE THREAD

**Issue by jaamison** [palantir/blueprint#3404] opened 2019-03-10 16:10 UTC
#### Environment

- __Package version(s)__: 3.14.1
- __Browser and OS versions__: OSX/FF65

#### Steps to reproduce

1. On Overlay docs page, open an overlay with `usePortal={false}`, `hasBackdrop={true}` and `canOutsideCloseClick={true}`
2. Click anywhere on the page outside of the overlay's container (overlay does not close)
3. Click anywhere inside the overlay's backdrop (overlay will close)

#### Actual behavior

An outside click somewhere on the document while an overlay is open does not close it.

#### Expected behavior

When an overlay is open with `canOutsideClick={true}`, any click outside of the overlay content should close it.

#### Possible solution

Provided that this is not the desired behavior and by design, inline (non-portal) overlays should always bind a mousedown listener to document, regardless of whether or not they have a backdrop.

**Comment by jaamison** [comment] 2019-03-12 04:08
In order to keep the component's behavior consistent. Right now it's already doing this when `hasBackdrop={false}`, so I think it would make sense for outside clicks to behave the same way when `hasBackdrop={true}` as well.

In other words, I don't think it makes sense to have an outside click in the same exact place close the overlay when it doesn't have a backdrop and not close it when it does have a backdrop.

**Comment by adidahiya** [comment] 2019-03-12 05:15
> I don't think it makes sense to have an outside click in the same exact place close the overlay when it doesn't have a backdrop and not close it when it does have a backdrop.

Ok, I see the potentially confusing API here... I believe the design of this "inconsistency" was motivated by the idea that the backdrop provides a visual affordance for closing the overlay/dialog when `canOutsideClickClose={true}`. It's been this way since we open sourced Blueprint, and likely was the same before that in the internal repo as long as these props existed. So when there is a backdrop, and outside clicks are allowed to close the overlay, it makes sense that the backdrop is a visual target which affords closing of the overlay.

This combination of `canOutsideClickClose={true} hasBackdrop={false}` is provided as an API for very special use cases, so I'd be curious to learn more about the context of your usage here before changing this low-level behavior.

**Comment by jaamison** [comment] 2019-03-12 05:55
I guess I had always thought of `canOutsideClickClose` and `hasBackdrop` as being purely orthogonal to each other, the former dictating the overlay's behavior and the latter specifying how the rest of the page is treated, but if one was really intended as a subset/modifier of the other then the current behavior makes more sense.

If the backdrop was specifically intended as a bounding region for close-triggering clicks, then this falls into the realm of architectural decisions, and no changes need to be made to the current behavior.

I have no pressing need for this change, my interest was purely in making sure that the semantics of the component's API were consistent and the underlying architecture is clean and streamlined. If the only issue here is confusing API terminology, then I don't see any reason to mess with things.

**Comment by jaamison** [comment] 2019-03-12 05:58
As a quick aside:

> This combination of canOutsideClickClose={true} hasBackdrop={false} is provided as an API for very special use cases,

This combo is the default for `<Popover>`

**Comment by adidahiya** [comment] 2019-03-12 18:45
> This combo is the default for <Popover>

ah, good point :) I was thinking in a dialog-centric way

I'm going to close this as "by design", but open to documentation changes which help explain the reasoning behind the interaction between these two props

**Closed** 2019-03-13 04:52 UTC
Labels: Domain: API, Package: core, Resolution: by design
