### ISSUE TITLE
components not compile with TypeScript 2.4.1 (latest release)

### ISSUE THREAD

**Issue by nisimjoseph** [palantir/blueprint#1314] opened 2017-07-04 19:47 UTC
### Bug report

- __Package version(s)__: 1.21.0
- __Browser and OS versions__: Compile time

#### Steps to reproduce

just use the component Button or any other, and compile it. lots of errors jump.

#### Actual behavior

list of compile time error

#### Expected behavior

clean build

**Comment by adidahiya** [comment] 2017-07-05 17:03
duplicate of https://github.com/palantir/blueprint/issues/1237, the fix will be available in the next release (hopefully this week)

**Closed by adidahiya** 2017-07-05 17:03 UTC
