### ISSUE TITLE
Scrollable Popup inside Scrollable Window 

### ISSUE THREAD

**Issue by lgnashold** [palantir/blueprint#6480] opened 2023-10-20 03:13 UTC
#### Environment

- __Package version(s)__:5.3.0
- __Browser and OS versions__:Mac OS Ventura 13.0, Chrome Version 118.0.5993.96 (Official Build) (arm64)

#### Question

Within a Table2 element, I'm using TruncatedFormat to display a popup on overly long cell texts. However, the table has a scrollbar, and the popover displayed by TruncatedFormat also has a scrollbar.

This means that when the popover is open, when the user scrolls, the internal popover and the table both scroll, which creates a very weird experience. Ideally, I'd like only the popover to scroll when it's opened and focused. 

How would I accomplish this?

**Comment by adidahiya** [comment] 2023-10-20 14:10
Duplicate of #5469

**Closed as completed by adidahiya** 2023-10-20 14:10 UTC
Labels: Resolution: duplicate
