### ISSUE TITLE
Support for attaching ContextMenu / Portal to pre-defined DOM node

### ISSUE THREAD

**Issue by rheinheimer** [palantir/blueprint#1990] opened 2018-01-11 14:49 UTC
I am trying to use a react-router Link within a menu triggered by a contextmenu event. From #185, I know I can do this within a Menu generally (assuming I don't use the MenuItem component but instead roll my own menu item). My general strategy is to use the ContextMenu function, i.e.:
`ContextMenu.show(menu, {left: e.clientX, top: e.clientY});`, where `menu` is a Menu component.

The issue here is that 1) react-router's Link needs to be within a Router context, but 2) ContextMenu, via Portal, attaches to a new child DOM component ["outside of the current component hierarchy"](http://blueprintjs.com/docs/#core/components/portal).

Is it possible, or desirable, to specify an existing DOM element on which to attach the Portal, specified via ContextMenu.show? E.g., if I have defined `<div id="my-popover"/>`, I could then use `ContextMenu.show(..., "my-popover")`.

EDIT: This is essentially the same issue as #1121

**Comment by adidahiya** [comment] 2018-01-11 16:04
Yeah, closing as a dupe of #1121. I think the fix is relatively simple, open to PRs

**Closed by adidahiya** 2018-01-11 16:04 UTC
