### ISSUE TITLE
Global hotkeys don't fire

### ISSUE THREAD

**Issue by waltonseymour** [palantir/blueprint#801] opened 2017-03-07 21:03 UTC
### Bug report

- __Package version(s)__: 1.7.0
- __Browser and OS versions__: Chrome 56.0.2924.87, MacOS 10.11.6

#### Steps to reproduce

1. On a component decorated with the `HotkeysTarget` decorator, define a global hotkey.
1. Now add `public componentDidMount = () => { console.log("hello"); }` to that component.
1. Load the page in the browser.
1. Press the global hotkey combination we just defined.

#### Actual behavior

The global hotkey does not trigger as expected. It is also not included in the hotkeys dialog (shown when you press <kbd>shift + S</kbd>. This occurs only when we use fat-arrow syntax to define `componentDidMount`; if we express as `public componentDidMount() {`, everything works as expected.

#### Expected behavior

Global hotkeys defined by a `HotkeysTarget` should work whether or not (and also in whichever manner) a `componentDidMount` is defined.

---

#### Original issue text

For some reason this setup does not capture command+s at all
```tsx
public renderHotkeys() {
        return <Hotkeys>
            <Hotkey
                global
                combo="mod+s"
                label="Save notebook"
                onKeyDown={(e) => {
                    e.preventDefault();
                    this.onSaveNotebook();
                }}
            />
        </Hotkeys>;
    }
```
But this one does when focused
```tsx
public renderHotkeys() {
        return <Hotkeys>
            <Hotkey
                combo="mod+s"
                label="Save notebook"
                onKeyDown={(e) => {
                    e.preventDefault();
                    this.onSaveNotebook();
                }}
            />
        </Hotkeys>;
    }
```
The page also has Monaco embedded in it which has its own hotkeys, so it might somehow be interfering.

**Comment by giladgray** [comment] 2017-03-07 21:34
I'll bet it is Monaco capturing the event. Can you try changing the hotkey to "mod+shift+s" and see if that works?

**Comment by waltonseymour** [comment] 2017-03-07 21:51
Tried changing to that, still no luck.

I also tried removing monaco and I still had the same issue. 😞

**Comment by cmslewis** [comment] 2017-03-07 22:22
Hi @waltonseymour, I'm going to take on this issue this week. Hopefully we can get things resolved by our release on Friday.

I'll need some help reproducing your issue. When you have a moment, could you construct for me a minimum viable scenario that manifests the bug you're seeing? We just chatted here in the office, and we suspect there's an issue between our `Hotkeys` component and something else in your setup. The behavior (unfortunately?) works as expected on our end.

In the meantime, I'll try to poke at our `Hotkeys` component to see if I can break it in a manner consistent with the one you're experiencing.

**Comment by waltonseymour** [comment] 2017-03-07 22:55
Found a repro for this.

Adding a event listener on `componentDidMount` breaks global hotkeys for me.

ie.
```
public componentDidMount = () => {
    console.log("hello");
}
```

**Comment by cmslewis** [comment] 2017-03-07 23:41
Thanks for that @waltonseymour. Will take a look.

**Comment by cmslewis** [comment] 2017-03-09 21:29
@waltonseymour Thanks for chatting with me offline. Looks like we can repro now. I've updated the issue description with the steps to reproduce.

**Comment by cmslewis** [comment] 2017-03-10 01:24
Spoke with @adidahiya. Seems like the solution here is to extend `tslint` with a rule that would prevent declaring React lifecycle methods with a fat arrow. Will track this effort in https://github.com/palantir/tslint-react/issues/74 and close this issue for now.

**Closed by cmslewis** 2017-03-10 01:24 UTC
Labels: Package: core, Status: work in progress, Type: bug
