### ISSUE TITLE
Card Layout in broken in v2

### ISSUE THREAD

**Issue by kudigaracoder** [palantir/blueprint#2189] opened 2018-02-28 10:16 UTC
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Safari 11.0.2

#### Steps to reproduce

1. Visit http://blueprintjs.com/docs/v2/#core/components/card

#### Actual behavior

<img width="880" alt="screen shot 2018-02-27 at 3 36 33 pm" src="https://user-images.githubusercontent.com/3305383/36782234-50dea860-1c9e-11e8-8d84-7e03092cb79d.png">

#### Expected behavior

<img width="888" alt="screen shot 2018-02-28 at 3 40 20 pm" src="https://user-images.githubusercontent.com/3305383/36782222-431891f0-1c9e-11e8-8f77-0eb9c183d993.png">

**Comment by llorca** [comment] 2018-02-28 18:48
@kudigaracoder Good catch! We'd gladly accept a PR for this, if you get a chance.

**Comment by llorca** [comment] 2018-02-28 18:56
also the issue is likely a docs one and not core: https://github.com/palantir/blueprint/issues/2190

**Comment by adidahiya** [comment] 2018-02-28 21:30
closing in favor of the docs issue #2167

**Closed by adidahiya** 2018-02-28 21:30 UTC
Labels: Domain: documentation, Type: bug
