### ISSUE TITLE
[Table] When enableFocus becomes true, show the focus cell right away

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1443] opened 2017-08-14 20:45 UTC
### Bug report

- __Package version(s)__: v1.24.0

#### Steps to reproduce

1. Set `enableFocus` to true on a `Table`.

#### Actual behavior

No focus cell shown until you make a selection, then it persists as expected.

#### Expected behavior

Show a focus cell right away.

**Comment by llorca** [comment] 2017-08-14 20:47
Dupe of https://github.com/palantir/blueprint/issues/1072?

**Comment by cmslewis** [comment] 2017-08-14 22:54
@llorca _Almost._ This is a piece of #1072 if we got through with that, specifically with respect to the `componentWillReceiveProps` logic.

**Closed** 2017-08-30 16:20 UTC
Labels: P3, Package: table, Type: bug
