### ISSUE TITLE
Sliders on inactive tabs default to wrong value - sliders show track fill when value is middle of range

### ISSUE THREAD

**Issue by iongion** [palantir/blueprint#3761] opened 2019-10-01 07:48 UTC
#### Environment

- __Package version(s)__: 

  - @blueprintjs/core `3.18.1`
  - @blueprintjs/icons `3.10.0`

- __Browser and OS versions__:

  - Chrome
  - Linux / Windows / OSX

Example here  https://codesandbox.io/s/heuristic-firefly-xbo31

#### Steps to reproduce

Two bugs:

1) When slider value is at range middle (0) and range is -10, 10, the blue track fill is shown drawn from min to middle, so from -10 to 0
2) Sliders on inactive tabs default to minimum value on first drag.

For **bug 1**

1. Go to **Tab 1**
2. See how the fill is being drawn from `min to range midpoint`

For **bug 2**

1. Go to **Tab 2**
2. Drag the slider to left or right.

#### Actual behavior

For bug 1 - track fill is shown
For bug 2 - when dragging the first time, the slider initially defaults to minimum value, it only happens on **Tab 2** so it might be an invalidation because the UI is invisible.

#### Expected behavior

For bug 1 - track fill **should not be shown**, it is confusing
For bug 2 - slider should not initially default to min, should just work as the slider on Tab 1

#### Possible solution

For bug 1 - no idea, I don't even know if it is a bug or a design decision
For bug 2 - this is clearly a bug, maybe force update of all components, when tab gets active

**EDIT** - For bug 2 - Adding `renderActiveTabPanelOnly` fixes the initial value problem of the slider.

**Comment by gsi-chao** [comment] 2019-10-01 22:58
I had the same problem and it was fixed by updating the version of @ blueprint/core to 3.15.1. Clean the node_modules by outdated nested dependencies

**Comment by adidahiya** [comment] 2020-12-02 20:27
duplicate of https://github.com/palantir/blueprint/issues/4109

**Closed by adidahiya** 2020-12-02 20:27 UTC
