### ISSUE TITLE
[TimePicker] Request: AM/PM vs. 24hr mode

### ISSUE THREAD

**Issue by spefley** [palantir/blueprint#1810] opened 2017-11-14 18:55 UTC
datetime v1.24.0

* it would be nice if it was more clear in the ui that the timepicker is a 24hr format. The way it is right now, it's possible users enter 1:00 meaning 1:00PM and never discover they are wrong

* it would be nice if there was an option to be in AM/PM format

**Comment by cmslewis** [comment] 2017-11-20 17:51
Just realized this is a dupe of #1409. I copied the text here into that issue's description. Closing.

**Comment by cmslewis** [comment] 2017-11-20 17:51
@spefley follow #1409 for further discussion!

**Closed by cmslewis** 2017-11-20 17:51 UTC
Labels: Package: datetime, Type: feature request
