### ISSUE TITLE
Support `sass` 4's `@extend SELECTOR, SELECTOR`

### ISSUE THREAD

**Issue by DTrejo** [palantir/blueprint#4088] opened 2020-04-23 03:00 UTC
Really enjoying blueprint in our project.

Goal: We'd like to use parcel to import and customize blueprint's CSS. This piece of syntax causes `sass 4` to break when it tries to import it. Would it be possible to make it `sass 4` compatible? Thanks!

The build error disappeared when I did this:
```diff
-@extend .#{$ns}-menu-item:hover;
+@extend .#{$ns}-menu-item, :hover;
```

---

https://github.com/palantir/blueprint/blob/efb0b5b03e61ff63ece0de918707bda1c742ca24/packages/core/src/components/menu/_submenu.scss#L19

---

## Full error message

```
compound selectors may no longer be extended.
Consider `@extend .bp3-menu-item, :hover` instead.
See http://bit.ly/ExtendCompound for details.

╷
19 │ @extend .#{$ns}-menu-item:hover;
│ ^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules/@blueprintjs/core/src/components/menu/_submenu.scss 19:15 root stylesheet
Error: compound selectors may no longer be extended.
Consider `@extend .bp3-menu-item, :hover` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
19 │       @extend .#{$ns}-menu-item:hover;
   │               ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@blueprintjs/core/src/components/menu/_submenu.scss 19:15  root stylesheet
```

Note: I also used this workaround to avoid needing to use svg-icon  https://github.com/palantir/blueprint/issues/2976#issuecomment-479231949  

Note: I also use this `.sassrc` to support `~` tilde in sass import paths:
```js
{
  "includePaths": [
    "node_modules"
  ]
}
```

**Comment by adidahiya** [comment] 2020-04-23 03:43
looks like a duplicate of #4032. we don't import Blueprint Sass files and customize them in our internal repos, so we haven't hit this bug. I would be open to a bugfix PR as long as it's not a breaking change

**Comment by DTrejo** [comment] 2020-04-24 16:23
Oops, sorry! Feel free to close / consolidate :)

Thanks for your hard work on blueprint!

**Closed** 2020-04-24 21:12 UTC
Labels: Resolution: duplicate
