### ISSUE TITLE
Links in documentation not rendered correctly

### ISSUE THREAD

**Issue by StefanoSGI** [palantir/blueprint#3562] opened 2019-05-22 17:14 UTC
At https://blueprintjs.com/docs/#core/components/icon
![Screenshot 2019-05-22 at 10 09 34 AM](https://user-images.githubusercontent.com/25331099/58194222-ce90e480-7c79-11e9-943c-41553bf95be1.png)

At https://blueprintjs.com/docs/#core/components/tooltip.props
![Screenshot 2019-05-22 at 10 12 12 AM](https://user-images.githubusercontent.com/25331099/58194417-5119a400-7c7a-11e9-8d46-2e3a9dca551a.png)

Other pages might be affected too.

Thank you!

**Comment by adidahiya** [comment] 2019-05-23 22:37
duplicate of #3487

**Closed by adidahiya** 2019-05-23 22:37 UTC
