### ISSUE TITLE
Cannot Run: gulp build

### ISSUE THREAD

**Issue by scottfr** [palantir/blueprint#150] opened 2016-11-14 21:52 UTC
### Bug Report

Cannot run 'gulp build' on a clean download of release 1.0.1. When I do, I get an error trying to import from the 'bourbon' package that doesn't seem to be installed. Installing the bourbon package does not seem to fix the issue.

#### Actual behavior:

```
[13:48:39] Using gulpfile ~/Downloads/blueprint-release-1.0.1/gulpfile.js
[13:48:39] Starting 'build'...
[13:48:39] Starting 'clean'...
[13:48:39] Finished 'clean' after 13 ms
[13:48:39] Starting 'compile'...
[13:48:39] Starting 'icons'...
[13:48:39] Finished 'icons' after 33 ms
[13:48:39] Starting 'sass-variables'...
[13:48:39] Finished 'sass-variables' after 292 ms
[13:48:39] Starting 'sass-compile-core'...
[13:48:39] Starting 'typescript-compile-core'...
[13:48:39] Starting 'copy-files-core'...
[13:48:39] Finished 'copy-files-core' after 101 μs
[13:48:39] Starting 'copy-files-datetime'...
[13:48:39] Finished 'copy-files-datetime' after 4.57 μs
[13:48:39] Starting 'copy-files-table'...
[13:48:39] Finished 'copy-files-table' after 5.05 μs
[13:48:39] Starting 'copy-files-docs'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: packages/core/src/common/_font-imports.scss
Error: File to import not found or unreadable: ../node_modules/bourbon/app/assets/stylesheets/bourbon
       Parent style sheet: /Users/fortmannroe/Downloads/blueprint-release-1.0.1/packages/core/src/common/_font-imports.scss
        on line 4 of packages/core/src/common/_font-imports.scss
>> @import "../node_modules/bourbon/app/assets/stylesheets/bourbon";
   ^

  at options.error (/Users/fortmannroe/Downloads/blueprint-release-1.0.1/node_modules/node-sass/lib/index.js:283:26)
```

#### Expected behavior:

The build process runs without error.

**Comment by giladgray** [comment] 2016-11-14 21:54
did you run `npm run bootstrap` before running `gulp`? this would suggest that dependencies for each package are not installed.

**Comment by giladgray** [comment] 2016-11-14 21:54
https://github.com/palantir/blueprint#development

**Comment by scottfr** [comment] 2016-11-14 22:02
Thanks for your help @giladgray, my mistake for not reading that.

It now get's farther but I encounter another error:

```
[13:59:08] Using gulpfile ~/Downloads/blueprint-release-1.0.1/gulpfile.js
[13:59:08] Starting 'build'...
[13:59:08] Starting 'clean'...
[13:59:08] Finished 'clean' after 23 ms
[13:59:08] Starting 'compile'...
[13:59:08] Starting 'icons'...
[13:59:08] Finished 'icons' after 33 ms
[13:59:08] Starting 'sass-variables'...
[13:59:08] Finished 'sass-variables' after 225 ms
[13:59:08] Starting 'sass-compile-core'...
[13:59:08] Starting 'typescript-compile-core'...
[13:59:08] Starting 'copy-files-core'...
[13:59:08] Finished 'copy-files-core' after 117 μs
[13:59:08] Starting 'copy-files-datetime'...
[13:59:08] Finished 'copy-files-datetime' after 3.96 μs
[13:59:08] Starting 'copy-files-table'...
[13:59:08] Finished 'copy-files-table' after 4.85 μs
[13:59:08] Starting 'copy-files-docs'...
[13:59:08] docs: 1 file copied
[13:59:08] Finished 'copy-files-docs' after 63 ms
[13:59:08] Starting 'copy-files'...
[13:59:08] Finished 'copy-files' after 33 μs

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: packages/core/src/common/_font-imports.scss
Error: no mixin named font-face

       Backtrace:
       	packages/core/src/common/_font-imports.scss:10
        on line 10 of packages/core/src/common/_font-imports.scss
>> @include font-face("Icons16", "#{$icon-font-path}/icons-16", $file-formats: $i
   ---------^

  at options.error (/Users/fortmannroe/Downloads/blueprint-release-1.0.1/node_modules/node-sass/lib/index.js:283:26)

```

**Comment by giladgray** [comment] 2016-11-14 22:33
[`font-face`](http://bourbon.io/docs/#font-face) is a bourbon mixin so this is likely related to your original issue. i've never seen this before so maybe it's an awkward version mismatch?

what version of node are you on? and what version of node-sass is installed? try `npm ls node-sass`

**Comment by giladgray** [comment] 2016-11-16 20:09
closing as we can't reproduce

**Closed by giladgray** 2016-11-16 20:09 UTC
