### ISSUE TITLE
Collapse does not type properly in TS v2.4

### ISSUE THREAD

**Issue by nomcopter** [palantir/blueprint#1307] opened 2017-06-30 20:47 UTC
```
    render(): React.DOMElement<{
        className: string;
        style: {
            height: string;
            overflowY: string;
            transition: string;
        };
    }, Element>;
```
Fails in the generated `.d.ts` with the improved weak typing checks `node_modules/@blueprintjs/core/dist/components/collapse/collapse.d.ts(46,32): error TS2559: Type '{ className: string; style: { height: string; overflowY: string; transition: string; }; }' has no properties in common with type 'DOMAttributes<Element>'.`

**Comment by llorca** [comment] 2017-06-30 20:50
Dupe of https://github.com/palantir/blueprint/issues/1237

The fix is coming with the next release sometimes next week 👍

**Comment by nomcopter** [comment] 2017-06-30 20:51
Well that was fast. Thanks!

**Closed by llorca** 2017-06-30 20:50 UTC
