### ISSUE TITLE
Emotion/Styled-Components based Blueprint

### ISSUE THREAD

**Issue by Slapbox** [palantir/blueprint#4021] opened 2020-03-21 20:49 UTC
#### Feature request

I know this is a major, major request and one that's at least been considered by the team before. 

Blueprint is amazing, but it would be almost unbelievable how powerful and amazing Blueprint would be if it used CSS in JS. 

As it stands now we are only leveraging a small part of this incredible framework, because styling it in the context of our project is quite difficult because it requires maintaining a parallel palette/theme to our primary theme used in our Emotion based components.

Thanks for your amazing work.

**Comment by adidahiya** [comment] 2020-03-24 15:16
Thanks for filing the issue, and yeah it's a major request which is not on the roadmap any time soon. I think it's fair to say this is a duplicate of #248 so I'm going to close it in favor of that thread. Let me know if you want a separate discussion.

**Closed** 2020-03-24 15:16 UTC
Labels: Resolution: duplicate, Type: feature request
