### ISSUE TITLE
InputGroup with no right element sets right padding of input element to zero

### ISSUE THREAD

**Issue by alexanderchr** [palantir/blueprint#1413] opened 2017-08-06 18:55 UTC
### Bug report

- __Package version(s)__: master branch
- __Browser and OS versions__: NA

#### Steps to reproduce

1. Render an InputGroup

#### Actual behavior

The text input rendered by the InputGroup has 10px left padding and 0 right padding, thanks to https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/inputGroup.tsx#L117.

#### Expected behavior

The text input rendered by the input group should have `$input-padding-horizontal` padding on both sides. (https://github.com/palantir/blueprint/blob/85a42b280a28ceb5c92700075aad5b3faac63cc1/packages/core/src/components/forms/_common.scss#L91)

I don't know if this is an issue in general, but it appeared to me when using DateInput as the inputs rendered through that component are 10px narrower than regular inputs.

**Comment by giladgray** [comment] 2018-04-03 19:05
duplicate of #1861

**Closed by giladgray** 2018-04-03 19:05 UTC
Labels: Package: core, Type: enhancement
