### ISSUE TITLE
[Popover] Buttons with tooltips have extra border in responsive button groups

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#630] opened 2017-02-06 23:06 UTC
### Bug report

- __Package version(s)__: 1.8.0
- __Browser and OS versions__: Chrome, OS X 10.11

#### Steps to reproduce

http://jsbin.com/gunicesume/edit?html,js,output

```ts
  <div className="pt-button-group pt-fill">
      <Tooltip text="foo">
          <Button iconName="timeline-bar-chart" />
      </Tooltip>
    ...
      <Tooltip text="bar">
          <Button iconName="grouped-bar-chart" />
      </Tooltip>
  </div>
```

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/723999/22670403/3f5b8bcc-ecc9-11e6-8ae2-2797c8c1c5e6.png)

#### Expected behavior

no extra border between buttons

**Comment by llorca** [comment] 2017-02-07 19:17
Weird, we haven't modified that, and the rule is still there:
```
&:not(.pt-minimal) {
    > .pt-popover-target:not(:first-child) .pt-button,
    > .pt-button:not(:first-child) {
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
    }

    > .pt-popover-target:not(:last-child) .pt-button,
    > .pt-button:not(:last-child) {
      margin-right: -$button-border-width;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
    }
  }
```

**Comment by llorca** [comment] 2017-02-07 19:20
Your JS Bin isn't working unfortunately, can you provide the DOM output from your JSX?

**Comment by adidahiya** [comment] 2017-02-08 01:36
```html
<div class="pt-button-group pt-fill"><span class="pt-popover-target"><button type="button" class="pt-button pt-icon-timeline-bar-chart"></button><!-- react-empty: 163 --></span><span class="pt-popover-target"><button type="button" class="pt-button pt-icon-timeline-line-chart pt-active pt-tether-target pt-tether-element-attached-top pt-tether-element-attached-center pt-tether-target-attached-bottom pt-tether-target-attached-center"></button><!-- react-empty: 183 --></span><span class="pt-popover-target"><button type="button" class="pt-button pt-icon-stacked-chart pt-tether-target pt-tether-element-attached-top pt-tether-element-attached-center pt-tether-target-attached-bottom pt-tether-target-attached-center"></button><!-- react-empty: 231 --></span></div>
```

js bin bug filed in linked ticket #631

**Comment by llorca** [comment] 2017-02-10 23:36
Uh-oh, flexbox problems... somehow negative margins don't work with `flex: 1` 🤔
Not sure how to go about fixing this

**Comment by llorca** [comment] 2017-02-24 19:49
Never mind my comment above ^ It works just fine in the docs: http://blueprintjs.com/docs/#components.button-group.css.fill

The issue is related to `.pt-popover-target`

**Comment by giladgray** [comment] 2017-02-27 19:37
moving to 2.x along with #724

**Comment by cmslewis** [comment] 2017-06-30 23:39
Adding the "[Popover]" prefix to remind us what the real issue is at a glance.

**Comment by giladgray** [comment] 2018-08-31 18:47
sure seems fixed now 
![image](https://user-images.githubusercontent.com/464822/44930570-99232000-ad13-11e8-994b-d3ff73fed6eb.png)

**Closed by giladgray** 2018-08-31 18:47 UTC
Labels: P2, Package: core, Type: bug, help wanted

**Comment by divinentd** [comment] 2019-03-26 17:11
This issue appears to be happening again, using the javascript API for a horizontal ButtonGroup with fill enabled and the buttons each wrapped in a Tooltip popover. With the example CSS above I can fix this manually, just wanted to let you know.

**Comment by adidahiya** [comment] 2019-03-26 19:53
@divinentd this issue is pretty old, would you mind filing a new one, ideally with a code sandbox link? thanks
