### ISSUE TITLE
DateInput doesn't appear over other elements when in ControlGroup

### ISSUE THREAD

**Issue by lsuss** [palantir/blueprint#2565] opened 2018-06-03 22:20 UTC
#### Environment

- __Package version(s)__: 2.3.1
- __Browser and OS versions__: Chrome 67 & Ubuntu 17.10

#### Steps to reproduce

```javascript
import React from "react";

import { ControlGroup } from "@blueprintjs/core";
import { DateInput, IDateFormatProps } from "@blueprintjs/datetime";

const jsDateFormatter: IDateFormatProps = {
  // note that the native implementation of Date functions differs between browsers
  formatDate: date => date.toLocaleDateString(),
  parseDate: str => new Date(str),
  placeholder: "M/D/YYYY",
};

export const App = () => (
  <>
    <ControlGroup>
      <DateInput {...jsDateFormatter} />
    </ControlGroup>
    <ControlGroup>
      <input type="text" className="pt-input" />
    </ControlGroup>
  </>
);
```
Both DateInput and text input have to be in a ControlGroup. Other popovers do not suffer of the same bug.

#### Actual behavior
![image](https://user-images.githubusercontent.com/801084/40891753-9e5a1880-678b-11e8-88df-efead57c9f74.png)
Second input goes over the datepicker popover.

#### Expected behavior
![image](https://user-images.githubusercontent.com/801084/40891769-c35eda6c-678b-11e8-899d-1563d0283368.png)
Datepicker to be over all other elements.

#### Possible solution
I was able to fix it by setting `transform: none` on `ControlGroup`.
```javascript
import React from "react";

import { ControlGroup } from "@blueprintjs/core";
import { DateInput, IDateFormatProps } from "@blueprintjs/datetime";

const jsDateFormatter: IDateFormatProps = {
  // note that the native implementation of Date functions differs between browsers
  formatDate: date => date.toLocaleDateString(),
  parseDate: str => new Date(str),
  placeholder: "M/D/YYYY",
};

export const App = () => (
  <>
    <ControlGroup style={{ transform: "none" }}>
      <DateInput {...jsDateFormatter} />
    </ControlGroup>
    <ControlGroup>
      <input type="text" className="pt-input" />
    </ControlGroup>
  </>
);
```

**Comment by giladgray** [comment] 2018-06-03 23:02
@lsuss this is a duplicate of #2368 and will be fixed by #2539

**Closed by giladgray** 2018-06-03 23:02 UTC
