### ISSUE TITLE
Error in @blueprintjs/datetime, DateInput component using google chrome: "TypeError: Cannot read property 'querySelectorAll' of null"

### ISSUE THREAD

**Issue by rubenmbm3** [palantir/blueprint#4766] opened 2021-06-16 21:48 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@blueprintjs/datetime@3.19.3` for the project I'm working on.

Error in @blueprintjs/datetime, DateInput component using google chrome: "TypeError: Cannot read property 'querySelectorAll' of null"

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@blueprintjs/datetime/lib/esm/dateInput.js b/node_modules/@blueprintjs/datetime/lib/esm/dateInput.js
index d0686bc..f616d2c 100644
--- a/node_modules/@blueprintjs/datetime/lib/esm/dateInput.js
+++ b/node_modules/@blueprintjs/datetime/lib/esm/dateInput.js
@@ -164,8 +164,8 @@ var DateInput = /** @class */ (function (_super) {
         _this.getLastTabbableElement = function () {
             // Popover contents are well structured, but the selector will need
             // to be updated if more focusable components are added in the future
-            var tabbableElements = _this.popoverContentEl.querySelectorAll("input, [tabindex]:not([tabindex='-1'])");
-            var numOfElements = tabbableElements.length;
+            var tabbableElements = (_this.popoverContentEl && _this.popoverContentEl.querySelectorAll("input, [tabindex]:not([tabindex='-1'])")) || {};
+            var numOfElements = tabbableElements.length || 0;
             // Keep track of the last focusable element in popover and add
             // a blur handler, so that when:
             // * user tabs to the next element, popover closes
@@ -198,14 +198,18 @@ var DateInput = /** @class */ (function (_super) {
             else if (relatedTarget != null) {
                 _this.unregisterPopoverBlurHandler();
                 _this.lastTabbableElement = _this.getLastTabbableElement();
-                _this.lastTabbableElement.addEventListener("blur", _this.handlePopoverBlur);
+                if(_this.lastTabbableElement) {
+                    _this.lastTabbableElement.addEventListener("blur", _this.handlePopoverBlur);
+                }
             }
         };
         _this.registerPopoverBlurHandler = function () {
             if (_this.popoverContentEl != null) {
                 _this.unregisterPopoverBlurHandler();
                 _this.lastTabbableElement = _this.getLastTabbableElement();
-                _this.lastTabbableElement.addEventListener("blur", _this.handlePopoverBlur);
+                if(_this.lastTabbableElement) {
+                    _this.lastTabbableElement.addEventListener("blur", _this.handlePopoverBlur);
+                }
             }
         };
         _this.unregisterPopoverBlurHandler = function () {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by adidahiya** [comment] 2021-06-17 20:04
Duplicate of https://github.com/palantir/blueprint/issues/4399, please upgrade your datetime package.

**Closed as completed by adidahiya** 2021-06-17 20:04 UTC
Labels: Resolution: duplicate
