### ISSUE TITLE
A JS example for the Tree component

### ISSUE THREAD

**Issue by sunabozu** [palantir/blueprint#541] opened 2017-01-25 12:52 UTC
I'm trying to understand how the `Tree` component works by reading your [example](https://github.com/palantir/blueprint/blob/master/packages/core/examples/treeExample.tsx), but I'm not familiar with TypeScript (especially with interfaces and generics) and it's hard for me to convert it into JavaScript. It would be very nice to have such an example for both languages.

**Comment by adidahiya** [comment] 2017-01-25 17:14
There isn't much TypeScript-specific syntax in that example, just the `interface` statement and some type param declarations (`: ITreeNode`), which you can ignore. I'm going to close this as a duplicate of #464 and we may continue discussion there.

**Closed by adidahiya** 2017-01-25 17:14 UTC
