### ISSUE TITLE
Table style is not in order.

### ISSUE THREAD

**Issue by fachilles** [palantir/blueprint#3322] opened 2019-01-30 07:58 UTC
I got one issue. Please help, what's going on?
#### Environment

- __Package version(s)__: 
![image](https://user-images.githubusercontent.com/3346188/51966551-c8e37900-24a7-11e9-81e3-178013c14628.png)

- __Browser and OS versions__: 

#### Actual behavior

![image](https://user-images.githubusercontent.com/3346188/51966458-83bf4700-24a7-11e9-9ab0-d1ea091f6086.png)

**Comment by giladgray** [comment] 2019-01-30 18:31
duplicate of https://github.com/palantir/blueprint/issues/2932. answer detailed there.

**Closed by giladgray** 2019-01-30 18:31 UTC
