### ISSUE TITLE
Input search field in Select component always loses focus if I use these component inside Drawer

### ISSUE THREAD

**Issue by Bielykh-Artem** [palantir/blueprint#3845] opened 2019-11-13 22:48 UTC

**Comment by adidahiya** [comment] 2019-11-14 16:46
please help me triage the issue by filling out the issue template

**Comment by Bielykh-Artem** [comment] 2019-11-14 19:05
I created video for you: https://drive.google.com/file/d/1T4fTUdhqWGTKNxQ9fiuZvZA6qIzyJ5I2/view?usp=sharing

**Comment by giuliano-december** [comment] 2019-11-28 03:15
@adidahiya putting `enforceFocus={false}` on the drawer solved that issue for me

**Comment by adidahiya** [comment] 2020-01-06 22:40
duplicate of #3854 (which has more info)

**Closed by adidahiya** 2020-01-06 22:40 UTC
