### ISSUE TITLE
Webpack warnings using CRA 5.0.0 (webpack 5)

### ISSUE THREAD

**Issue by odusseys** [palantir/blueprint#5111] opened 2022-01-31 10:55 UTC
#### Environment

- __Package version(s)__: 
  "@blueprintjs/core": "^3.52.0",
    "@blueprintjs/datetime": "^3.23.19",
    "@blueprintjs/popover2": "^0.12.9",
- __Operating System__:  OSX 12.1
- __Browser name and version__: Chrome (irrelevant)

#### Steps to reproduce

Install blueprint using create-react-app 5.0.0, import styles using 
```
import "@blueprintjs/core/lib/css/blueprint.css";
import "@blueprintjs/datetime/lib/css/blueprint-datetime.css";
import "@blueprintjs/popover2/lib/css/blueprint-popover2.css";
```

#### Actual behavior

Webpack throws a bunch of warnings for missing scss files in source map parsing:

```
WARNING in ./node_modules/@blueprintjs/popover2/lib/css/blueprint-popover2.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/@blueprintjs/popover2/lib/css/blueprint-popover2.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map [...]
```

#### Expected behavior

No warnings thrown 

#### Possible solution

Include missing scss files in build

**Comment by zachkirsch** [comment] 2022-02-27 09:35
I think this is the same root cause as https://github.com/palantir/blueprint/issues/3500 - incorrect paths to source maps

**Comment by zachkirsch** [comment] 2022-03-03 18:37
Confirmed fixed by https://github.com/palantir/blueprint/pull/5146 in `4.0.0-rc.0`

**Closed as completed** 2022-03-07 19:25 UTC
Labels: Domain: tooling, P2, help wanted
