### ISSUE TITLE
[TagInput] Typing text into the input doesn't appear

### ISSUE THREAD

**Issue by davidlipo** [palantir/blueprint#1963] opened 2017-12-22 13:06 UTC
### Bug report

- __Package version(s)__: Labs 0.14.1
- __Browser and OS versions__: Chrome 62, Mac OS 10.12.6

#### Steps to reproduce

1. To go http://blueprintjs.com/docs/#labs/tag-input
2. Enter text in the input box

#### Actual behavior

The input stays empty

#### Expected behavior

The text entered will show up in the text box

**Comment by giladgray** [comment] 2017-12-22 19:29
duplicate of #1919, fixed in labs @ 0.14.2

**Closed by giladgray** 2017-12-22 19:29 UTC
