### ISSUE TITLE
Hotkeys: ability to trigger the dialog from any code

### ISSUE THREAD

**Issue by warpdesign** [palantir/blueprint#3135] opened 2018-11-07 22:35 UTC
Reading the docs, it seems there is no way to bring the `hotkeys dialog` other than by pressing the `dialog hotkey`. It would be great if there was an API to bring it from anywhere, for exemple, a button, a menu,..

**Comment by giladgray** [comment] 2018-11-16 15:38
duplicate of #1590  (also #1028 is related)

**Closed by giladgray** 2018-11-16 15:38 UTC
