### ISSUE TITLE
Some components ignore a data-* attributes

### ISSUE THREAD

**Issue by bossa-jpg** [palantir/blueprint#5327] opened 2022-05-26 05:46 UTC
#### Environment

- __Package version(s)__: blueprintjs/core@4.3.0, blueprintjs/datetime@4.2.0
- __Operating System__: macos
- __Browser name and version__: chrome 101.0.4951.64 

#### Code Sandbox
I found this problem for `<Alert>`, `<TimePicker>` and `<NonIdealState>` components

Link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-6drvc0?file=/src/index.tsx

#### Steps to reproduce

1. Add data-* attribute to component
2. Check for the presence of this attribute in DevTools

#### Actual behavior
The component does not have a data-* attribute

#### Expected behavior
The component has a data-* attribute

**Comment by adidahiya** [comment] 2022-05-26 13:23
Duplicate of #3763, please comment there with the components you wish to use `data-*` attributes with.

**Closed as completed by adidahiya** 2022-05-26 13:23 UTC
Labels: Resolution: duplicate

**Comment by Gayathri-Kesavakannan** [comment] 2022-08-23 20:51
How to add data-* for accordion (button) and form (label) ?
