### ISSUE TITLE
DateRangePicker : changing "value" (controlled) only updates Date, but not Time

### ISSUE THREAD

**Issue by eleveurdechevres** [palantir/blueprint#3967] opened 2020-02-17 10:28 UTC
#### Environment

- __Package version(s)__: datetime 3.15.2
- __Browser and OS versions__: Chrome 79.0.3945.130

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

                                <DateRangePicker
                                    value={this.selectedDateRange}
                                    onChange={(selectedDateRange: DateRange) => this.selectedDateRange = selectedDateRange}
                                    allowSingleDayRange={true}
                                    contiguousCalendarMonths={false}
                                    timePrecision={'second'}
                                    shortcuts={false}
                                    timePickerProps={{
                                        useAmPm: true
                                    }}
                                />

#### Actual behavior

In controlled mode, if i change manually this.selectedDateRange in another component, the date is modified in the DateRangePicker, but not the time

#### Expected behavior

TimePicker values must be updated when range value is changed.

**Comment by adidahiya** [comment] 2020-02-27 19:24
@eleveurdechevres it would really help if you provided a repro by forking the code sandbox so I can further investigate

**Comment by eleveurdechevres** [comment] 2020-03-03 14:26
Hello !
Sorry, I was on holidays ^^.

Here is a repo for testing :
https://github.com/eleveurdechevres/DateRangePicker_test

- The buttons permit to choose different DateRanges.
- "From date" and "To date" are displayed on the bottom (date.toIsoString(), perhaps it is not the best method)
- You see that when you click on the buttons, the date is selected in the picker, but the time is not.
I have seen also bad dates, just before sending you this message, perhaps there is another little problem due to the example ?

Have a good day,
Freddy

**Comment by eleveurdechevres** [comment] 2020-03-03 14:34
Note : the other problem I saw : by default the time is 12:00:00 AM => it indicates incorrect dates

**Comment by MonkeyAndres** [comment] 2020-03-24 16:22
Same here!

**Comment by sharpcoder7** [comment] 2020-08-03 16:17
This component uses areRangesEqual function which does not check if time was changed.
Also, this component has time property in its state which is not updated in a controlled mode, so time input boxes are not updated as well

**Comment by adidahiya** [comment] 2022-08-22 20:38
Duplicate of #5502

**Closed by adidahiya** 2022-08-22 20:38 UTC
Labels: Package: datetime, Status: needs more info
