### ISSUE TITLE
Tooltip color not changing after theme switch (only on first hover).

### ISSUE THREAD

**Issue by neevany** [palantir/blueprint#388] opened 2016-12-26 06:46 UTC
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: Version 57.0.2962.0 (Official Build) canary (64-bit), Mac Os Sierra 10.12 (16A323)

#### Steps to reproduce

1. switch theme
2.hover on tooltip

#### Actual behaviour

tooltip color showing color of old theme  (only the first hover after theme switch)

#### Expected behaviour

tooltip color should be of selected theme

**Comment by adidahiya** [comment] 2016-12-26 17:14
duplicate of #163

**Closed by adidahiya** 2016-12-26 17:14 UTC
