### ISSUE TITLE
V2 Toasts Rendering Strangely

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2272] opened 2018-03-19 20:11 UTC
Hey there,

After upgrading to Blueprint v2 my Toasts have started looking like this: 

![image](https://user-images.githubusercontent.com/2730609/37619439-c2e2b76c-2b76-11e8-9cc7-777401d7e581.png)

Here's how I manage toasts in my app: 

```
import { Position, Toaster, Intent } from "@blueprintjs/core";


const toastr = Toaster.create({
  className: "top-toaster",
  position: Position.TOP
});


const generateToast = intent => (message) => {
  
  toastr.show({
    intent,
    message
  }, "intent"); 
};

if (!window.toastr) window.toastr = {};
if (!window.toastr.success) {
  window.toastr.success = generateToast(Intent.SUCCESS);
}
```

Any ideas what might have changed? 

Thanks!

**Comment by llorca** [comment] 2018-03-19 20:46
Dupe of https://github.com/palantir/blueprint/issues/2232

**Comment by giladgray** [comment] 2018-03-19 20:47
this is fixed but not released

**Closed by giladgray** 2018-03-19 20:47 UTC
Labels: Package: core, Resolution: duplicate, Type: bug

**Comment by tnrich** [comment] 2018-03-19 20:51
Awesome thanks!

**Comment by tnrich** [comment] 2018-03-30 20:15
@giladgray has this been released yet?

**Comment by llorca** [comment] 2018-03-30 20:34
@tnrich yessir: http://blueprintjs.com/docs/v2/#core/components/toast
