### ISSUE TITLE
TimePicker: not possible to replace hour digits from keyboard. Backspace not functional either.

### ISSUE THREAD

**Issue by jayarjo** [palantir/blueprint#3719] opened 2019-09-01 11:50 UTC
#### Environment

- __Package version(s)__: @blueprintjs/datetime v3.12.0

Not possible to enter hours from keyboard. Backspace deletes only one digit, another one not replaceable in case of two digit hour.

Minutes are handled properly. I think logic for hours should be the same.

Also what's the reasoning behind only one zero placeholder for hours?

**Comment by adidahiya** [comment] 2019-09-04 19:20
Duplicate of #3648

**Closed by adidahiya** 2019-09-04 19:20 UTC
