### ISSUE TITLE
Date range input selection will close the whole dialog

### ISSUE THREAD

**Issue by gasolin** [palantir/blueprint#2759] opened 2018-08-03 09:29 UTC
#### Environment

- __Package version(s)__: 3.0.1(core) 3.0.0(datetime)
- __Browser and OS versions__: firefox 60.0.2 / ubuntu 16.04

#### Steps to reproduce

1. Put a Date range input inside dialog component, like

```
 <Dialog
  icon="calendar"
  onClose={this.handleDialogClose}
   title={intl.formatMessage({ id: 'timeframe.custom' })}
   autoFocus
   canEscapeKeyClose
   canOutsideClickClose
   enforceFocus
   usePortal
   isOpen={this.state.isOpen}
  >
          <div className={Classes.DIALOG_BODY}>
            <DateRangeInput
              allowSingleDayRange
              closeOnSelection
              formatDate={dateFormat.formatDate}
              parseDate={dateFormat.parseDate}
              onChange={this.handleRangeChange}
            />
           </div>
</Dialog>
```

1. select date with Date range input

#### Actual behavior

1. when a date is selected, the whole dialog is also closed

when showing same date range input without dialog, it behave normally

#### Expected behavior

1. when a date is selected, the whole dialog is keep showing

#### Possible solution

The dialog and Date range input might share the same event or property to close the dialog/popup. 
Should use the separate one so the behavior won't interfere

**Comment by threeid** [comment] 2018-08-03 11:15
https://github.com/palantir/blueprint/pull/2756 will fix this.

**Comment by giladgray** [comment] 2018-08-03 16:47
yeah literally about to be fixed. also a duplicate of #2753.

**Closed** 2018-08-03 20:58 UTC
